import Beal.«Beal.General».ProjectiveChartComparison

/-!
The chart map from a graded ring to its homogeneous quotient.
For a homogeneous denominator with nonzero powers in the quotient,
the chart map is surjective. When the homogeneous ideal is generated
by a base scalar, its kernel is generated by the corresponding
degree-zero scalar fraction. This identifies the three quotient chart
rings used for the split special fibre; scheme gluing and comparison
with the actual pullback are separate.
-/

namespace Beal.General

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
variable (𝒜 : ℕ → Submodule R A) [GradedAlgebra 𝒜]

/-- A nonzero homogeneous element has a unique degree. -/
theorem homogeneous_degree_unique (x : A) (m n : ℕ)
    (hm : x ∈ 𝒜 m) (hn : x ∈ 𝒜 n) (hx : x ≠ 0) : m = n := by
  classical
  by_contra h
  have hsame : (GradedRing.proj 𝒜 n) x = x := by
    rw [GradedRing.proj_apply]
    exact DirectSum.decompose_of_mem_same 𝒜 hn
  have hother : (GradedRing.proj 𝒜 n) x = 0 := by
    rw [GradedRing.proj_apply]
    exact DirectSum.decompose_of_mem_ne 𝒜 hm h
  exact hx (hsame.symm.trans hother)

/-- If a homogeneous element belongs to the ideal generated by a base
scalar, it has a factorization with a homogeneous cofactor of the same
degree. -/
theorem homogeneous_scalar_ideal_factor
    (t : R) (x : A) (m : ℕ)
    (hx : x ∈ 𝒜 m)
    (hmem : x ∈ Ideal.span {algebraMap R A t}) :
    ∃ b : A, b ∈ 𝒜 m ∧ x = algebraMap R A t * b := by
  classical
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hmem
  let c := GradedRing.proj 𝒜 m b
  have hc : c ∈ 𝒜 m := by
    change GradedRing.proj 𝒜 m b ∈ 𝒜 m
    rw [GradedRing.proj_apply]
    exact ((DirectSum.decompose 𝒜 b) m).property
  have hident (z : A) :
      GradedRing.proj 𝒜 m z = GradedAlgebra.proj 𝒜 m z := by
    rw [GradedRing.proj_apply, GradedAlgebra.proj_apply]
  have hproj : GradedRing.proj 𝒜 m (algebraMap R A t * b) =
      algebraMap R A t * c := by
    simpa only [hident, Algebra.smul_def] using
      (map_smul (GradedAlgebra.proj 𝒜 m) t b)
  refine ⟨c, hc, ?_⟩
  calc
    x = GradedRing.proj 𝒜 m x := by
      rw [GradedRing.proj_apply]
      exact (DirectSum.decompose_of_mem_same 𝒜 hx).symm
    _ = GradedRing.proj 𝒜 m (algebraMap R A t * b) := by
      rw [mul_comm, hb]
    _ = algebraMap R A t * c := hproj

/-- Powers of a homogeneous element retain their expected degree
in the quotient grading. -/
theorem homogeneousQuotient_pow_mem
    (I : Ideal A) (f : A) (d : ℕ) (hf : f ∈ 𝒜 d) (n : ℕ) :
    (Ideal.Quotient.mk I f) ^ n ∈
      homogeneousQuotientComponent 𝒜 I (n * d) := by
  have hpow : ∀ k : ℕ, f ^ k ∈ 𝒜 (k * d) := by
    intro k
    induction k with
    | zero => simpa only [zero_mul, pow_zero] using (SetLike.one_mem_graded 𝒜)
    | succ k ih =>
        simpa only [pow_succ, Nat.succ_mul] using
          (SetLike.GradedMul.mul_mem ih hf)
  apply Submodule.mem_map.mpr
  exact ⟨f ^ n, hpow n, by simp⟩

/-- The natural degree-zero map on the basic open at `f`,
where the quotient carries the inherited homogeneous grading. -/
noncomputable def homogeneousQuotientAwayMap
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (f : A) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    HomogeneousLocalization.Away 𝒜 f →+*
      HomogeneousLocalization.Away
        (homogeneousQuotientComponent 𝒜 I) (Ideal.Quotient.mk I f) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  apply gradedLocalizationMap 𝒜 (homogeneousQuotientComponent 𝒜 I)
    (Ideal.Quotient.mk I)
  · intro a ha
    obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff a f).mp ha
    apply (Submonoid.mem_powers_iff _ _).mpr
    exact ⟨n, by simpa only [map_pow] using
      (congrArg (Ideal.Quotient.mk I) hn)⟩
  · intro n a ha
    exact Submodule.mem_map.mpr ⟨a, ha, rfl⟩

/-- The corresponding map on the double localization, with both
coordinate denominators inverted. -/
noncomputable def homogeneousQuotientDoubleMap
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜) (f g : A) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    HomogeneousLocalization 𝒜 (Submonoid.powers f ⊔ Submonoid.powers g) →+*
      HomogeneousLocalization (homogeneousQuotientComponent 𝒜 I)
        (Submonoid.powers (Ideal.Quotient.mk I f) ⊔
          Submonoid.powers (Ideal.Quotient.mk I g)) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  apply gradedLocalizationMap 𝒜 (homogeneousQuotientComponent 𝒜 I)
    (Ideal.Quotient.mk I)
  · apply sup_le
    · intro a ha
      obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff a f).mp ha
      apply Submonoid.mem_sup_left
      exact (Submonoid.mem_powers_iff _ _).mpr
        ⟨n, by simpa only [map_pow] using
          (congrArg (Ideal.Quotient.mk I) hn)⟩
    · intro a ha
      obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff a g).mp ha
      apply Submonoid.mem_sup_right
      exact (Submonoid.mem_powers_iff _ _).mpr
        ⟨n, by simpa only [map_pow] using
          (congrArg (Ideal.Quotient.mk I) hn)⟩
  · intro n a ha
    exact Submodule.mem_map.mpr ⟨a, ha, rfl⟩

/-- The `f` chart quotient map restricts to the double-localization
map, so it agrees with the overlap comparison. -/
theorem homogeneousQuotientAwayMap_double_left
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜) (f g : A) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    (HomogeneousLocalization.mapId (homogeneousQuotientComponent 𝒜 I)
        (le_sup_left : Submonoid.powers (Ideal.Quotient.mk I f) ≤
          Submonoid.powers (Ideal.Quotient.mk I f) ⊔
            Submonoid.powers (Ideal.Quotient.mk I g))).comp
      (homogeneousQuotientAwayMap 𝒜 I hI f) =
    (homogeneousQuotientDoubleMap 𝒜 I hI f g).comp
      (HomogeneousLocalization.mapId 𝒜
        (le_sup_left : Submonoid.powers f ≤
          Submonoid.powers f ⊔ Submonoid.powers g)) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  apply RingHom.ext
  intro s
  obtain ⟨v, rfl⟩ := HomogeneousLocalization.mk_surjective s
  simp only [RingHom.comp_apply, HomogeneousLocalization.mapId,
    HomogeneousLocalization.map_mk, homogeneousQuotientAwayMap,
    homogeneousQuotientDoubleMap, gradedLocalizationMap_mk]
  rfl

/-- The `g` chart has the same double-localization map as the
restriction of the `f` chart. -/
theorem homogeneousQuotientAwayMap_double_right
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜) (f g : A) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    (HomogeneousLocalization.mapId (homogeneousQuotientComponent 𝒜 I)
        (le_sup_right : Submonoid.powers (Ideal.Quotient.mk I g) ≤
          Submonoid.powers (Ideal.Quotient.mk I f) ⊔
            Submonoid.powers (Ideal.Quotient.mk I g))).comp
      (homogeneousQuotientAwayMap 𝒜 I hI g) =
    (homogeneousQuotientDoubleMap 𝒜 I hI f g).comp
      (HomogeneousLocalization.mapId 𝒜
        (le_sup_right : Submonoid.powers g ≤
          Submonoid.powers f ⊔ Submonoid.powers g)) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  apply RingHom.ext
  intro s
  obtain ⟨v, rfl⟩ := HomogeneousLocalization.mk_surjective s
  simp only [RingHom.comp_apply, HomogeneousLocalization.mapId,
    HomogeneousLocalization.map_mk, homogeneousQuotientAwayMap,
    homogeneousQuotientDoubleMap, gradedLocalizationMap_mk]
  rfl

/-- If no power of the image of a homogeneous denominator vanishes,
every degree-zero fraction in the quotient chart lifts to a fraction
in the integral chart. The kernel comparison is a separate step. -/
theorem homogeneousQuotientAwayMap_surjective
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (f : A) (d : ℕ) (hf : f ∈ 𝒜 d)
    (hpow : ∀ n : ℕ, (Ideal.Quotient.mk I f) ^ n ≠ 0) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    Function.Surjective (homogeneousQuotientAwayMap 𝒜 I hI f) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  intro t
  obtain ⟨v, rfl⟩ := HomogeneousLocalization.mk_surjective t
  obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff
    (v.den : A ⧸ I) (Ideal.Quotient.mk I f)).mp v.den_mem
  have hdegree : v.deg = n * d :=
    homogeneous_degree_unique (homogeneousQuotientComponent 𝒜 I)
      (v.den : A ⧸ I) v.deg (n * d) v.den.property
      (by rw [← hn]; exact homogeneousQuotient_pow_mem 𝒜 I f d hf n)
      (by intro hz; exact hpow n (hn.trans hz))
  obtain ⟨a, ha, haq⟩ := Submodule.mem_map.mp v.num.property
  have hf_pow : f ^ n ∈ 𝒜 v.deg := by
    rw [hdegree]
    have hpower (k : ℕ) : f ^ k ∈ 𝒜 (k * d) := by
      induction k with
      | zero => simpa only [zero_mul, pow_zero] using (SetLike.one_mem_graded 𝒜)
      | succ k ih =>
          simpa only [pow_succ, Nat.succ_mul] using
            (SetLike.GradedMul.mul_mem ih hf)
    exact hpower n
  let w : HomogeneousLocalization.NumDenSameDeg 𝒜 (Submonoid.powers f) :=
    ⟨v.deg, ⟨a, ha⟩, ⟨f ^ n, hf_pow⟩,
      (Submonoid.mem_powers_iff _ _).mpr ⟨n, rfl⟩⟩
  refine ⟨HomogeneousLocalization.mk w, ?_⟩
  change gradedLocalizationMap 𝒜 (homogeneousQuotientComponent 𝒜 I)
      (Ideal.Quotient.mk I) _ _ (HomogeneousLocalization.mk w) =
    HomogeneousLocalization.mk v
  rw [gradedLocalizationMap_mk]
  change (Ideal.Quotient.mk I) a = (v.num : A ⧸ I) at haq
  simp [w, haq, hn]

/-- A fraction maps to zero in the quotient basic chart exactly when
some power of the chart denominator sends its numerator into the
homogeneous ideal. -/
theorem homogeneousQuotientAwayMap_mk_eq_zero_iff
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜) (f : A)
    (v : HomogeneousLocalization.NumDenSameDeg 𝒜 (Submonoid.powers f)) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    homogeneousQuotientAwayMap 𝒜 I hI f (HomogeneousLocalization.mk v) = 0 ↔
      ∃ n : ℕ, f ^ n * (v.num : A) ∈ I := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  let Q := Submonoid.powers (Ideal.Quotient.mk I f)
  have hval :
      (homogeneousQuotientAwayMap 𝒜 I hI f
        (HomogeneousLocalization.mk v)).val =
        (Localization.mk (Ideal.Quotient.mk I (v.num : A))
          ⟨Ideal.Quotient.mk I (v.den : A), by
            obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff (v.den : A) f).mp v.den_mem
            exact (Submonoid.mem_powers_iff _ _).mpr
              ⟨n, by simpa only [map_pow] using
                (congrArg (Ideal.Quotient.mk I) hn)⟩⟩ :
          Localization Q) := by
    change (gradedLocalizationMap 𝒜 (homogeneousQuotientComponent 𝒜 I)
      (Ideal.Quotient.mk I) _ _
      (HomogeneousLocalization.mk v)).val = _
    rw [gradedLocalizationMap_mk, HomogeneousLocalization.val_mk]
  constructor
  · intro hz
    have hv : (homogeneousQuotientAwayMap 𝒜 I hI f
        (HomogeneousLocalization.mk v)).val = 0 := by
      rw [hz, HomogeneousLocalization.val_zero]
    rw [hval] at hv
    rw [Localization.mk_eq_mk'] at hv
    obtain ⟨m, hm⟩ :=
      (IsLocalization.mk'_eq_zero_iff
        (Ideal.Quotient.mk I (v.num : A))
        ⟨Ideal.Quotient.mk I (v.den : A), by
          obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff (v.den : A) f).mp v.den_mem
          exact (Submonoid.mem_powers_iff _ _).mpr
            ⟨n, by simpa only [map_pow] using
              (congrArg (Ideal.Quotient.mk I) hn)⟩⟩).mp hv
    obtain ⟨n, hn⟩ :=
      (Submonoid.mem_powers_iff (m : A ⧸ I) (Ideal.Quotient.mk I f)).mp m.property
    refine ⟨n, Ideal.Quotient.eq_zero_iff_mem.mp ?_⟩
    simpa only [map_pow, map_mul, hn] using hm
  · rintro ⟨n, hn⟩
    apply HomogeneousLocalization.val_injective Q
    rw [HomogeneousLocalization.val_zero, hval]
    rw [Localization.mk_eq_mk']
    apply (IsLocalization.mk'_eq_zero_iff
      (Ideal.Quotient.mk I (v.num : A))
      ⟨Ideal.Quotient.mk I (v.den : A), by
        obtain ⟨k, hk⟩ := (Submonoid.mem_powers_iff (v.den : A) f).mp v.den_mem
        exact (Submonoid.mem_powers_iff _ _).mpr
          ⟨k, by simpa only [map_pow] using
            (congrArg (Ideal.Quotient.mk I) hk)⟩⟩).mpr
    refine ⟨⟨(Ideal.Quotient.mk I f) ^ n,
      (Submonoid.mem_powers_iff _ _).mpr ⟨n, rfl⟩⟩, ?_⟩
    simpa only [← map_pow, ← map_mul] using
      (Ideal.Quotient.eq_zero_iff_mem.mpr hn)

/-- A base scalar represented by the degree-zero fraction over one. -/
noncomputable def homogeneousScalarAway (f : A) (t : R) :
    HomogeneousLocalization.Away 𝒜 f :=
  HomogeneousLocalization.mk
    ⟨0, ⟨algebraMap R A t, SetLike.algebraMap_mem_graded 𝒜 t⟩,
      ⟨1, SetLike.one_mem_graded 𝒜⟩, Submonoid.one_mem _⟩

/-- On a homogeneous basic chart, quotienting the homogeneous
coordinate ring by a scalar ideal has exactly the scalar-generated
kernel on degree-zero fractions. -/
theorem homogeneousQuotientAwayMap_ker
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (t : R) (hgen : I = Ideal.span {algebraMap R A t})
    (f : A) (d : ℕ) (hf : f ∈ 𝒜 d) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    RingHom.ker (homogeneousQuotientAwayMap 𝒜 I hI f) =
      Ideal.span {homogeneousScalarAway 𝒜 f t} := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  apply le_antisymm
  · intro x hx
    obtain ⟨v, rfl⟩ := HomogeneousLocalization.mk_surjective x
    obtain ⟨n, hn⟩ :=
      (homogeneousQuotientAwayMap_mk_eq_zero_iff 𝒜 I hI f v).mp hx
    have hpower (k : ℕ) : f ^ k ∈ 𝒜 (k * d) := by
      induction k with
      | zero => simpa only [zero_mul, pow_zero] using (SetLike.one_mem_graded 𝒜)
      | succ k ih =>
          simpa only [pow_succ, Nat.succ_mul] using
            (SetLike.GradedMul.mul_mem ih hf)
    have hf_pow := hpower n
    obtain ⟨b, hb, hfactor⟩ :=
      homogeneous_scalar_ideal_factor 𝒜 t
        (f ^ n * (v.num : A)) (n * d + v.deg)
        (SetLike.GradedMul.mul_mem hf_pow v.num.property)
        (by simpa only [hgen] using hn)
    let w : HomogeneousLocalization.NumDenSameDeg 𝒜 (Submonoid.powers f) :=
      ⟨v.deg + n * d, ⟨b, by simpa only [add_comm] using hb⟩,
        ⟨(v.den : A) * f ^ n, SetLike.GradedMul.mul_mem
          v.den.property hf_pow⟩,
        (Submonoid.powers f).mul_mem v.den_mem
          ((Submonoid.mem_powers_iff _ _).mpr ⟨n, rfl⟩)⟩
    have hfraction :
        HomogeneousLocalization.mk v =
          HomogeneousLocalization.mk w * homogeneousScalarAway 𝒜 f t := by
      apply HomogeneousLocalization.val_injective (Submonoid.powers f)
      simp only [HomogeneousLocalization.val_mul,
        HomogeneousLocalization.val_mk, homogeneousScalarAway,
        Localization.mk_mul]
      rw [Localization.mk_eq_mk_iff, Localization.r_eq_r']
      refine ⟨1, ?_⟩
      simp only [Submonoid.coe_one, one_mul, w]
      calc
        ((v.den : A) * f ^ n * 1) * (v.num : A) =
            (v.den : A) * (f ^ n * (v.num : A)) := by ring
        _ = (v.den : A) * (algebraMap R A t * b) := by rw [hfactor]
        _ = (v.den : A) * (b * algebraMap R A t) := by ring
    rw [hfraction]
    exact (Ideal.span {homogeneousScalarAway 𝒜 f t}).mul_mem_left _
      (Ideal.subset_span (Set.mem_singleton _))
  · apply Ideal.span_le.mpr
    intro a ha
    rcases Set.mem_singleton_iff.mp ha with rfl
    apply (homogeneousQuotientAwayMap_mk_eq_zero_iff 𝒜 I hI f
      ⟨0, ⟨algebraMap R A t, SetLike.algebraMap_mem_graded 𝒜 t⟩,
        ⟨1, SetLike.one_mem_graded 𝒜⟩, Submonoid.one_mem _⟩).mpr
    refine ⟨0, ?_⟩
    simpa only [pow_zero, one_mul, hgen] using
      (Ideal.subset_span (Set.mem_singleton (algebraMap R A t)))

/-- Degree-zero localization commutes with quotient by a base
scalar on a homogeneous basic chart, provided the quotient denominator
is not nilpotent. This is an isomorphism of chart rings, not yet a
gluing of schemes. -/
noncomputable def homogeneousQuotientAwayRingEquiv
    (I : Ideal A) (hI : I.IsHomogeneous 𝒜)
    (t : R) (hgen : I = Ideal.span {algebraMap R A t})
    (f : A) (d : ℕ) (hf : f ∈ 𝒜 d)
    (hpow : ∀ n : ℕ, (Ideal.Quotient.mk I f) ^ n ≠ 0) :
    letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
      homogeneousQuotientGrading 𝒜 I hI
    (HomogeneousLocalization.Away 𝒜 f ⧸
      Ideal.span {homogeneousScalarAway 𝒜 f t}) ≃+*
      HomogeneousLocalization.Away
        (homogeneousQuotientComponent 𝒜 I) (Ideal.Quotient.mk I f) := by
  letI : GradedAlgebra (homogeneousQuotientComponent 𝒜 I) :=
    homogeneousQuotientGrading 𝒜 I hI
  exact (Ideal.quotEquivOfEq
    (homogeneousQuotientAwayMap_ker 𝒜 I hI t hgen f d hf).symm).trans
      (RingHom.quotientKerEquivOfSurjective
        (homogeneousQuotientAwayMap_surjective 𝒜 I hI f d hf hpow))

end Beal.General

namespace Beal.General

/-- The actual special-fibre ideal is generated by the base scalar
`2` inside the integral homogeneous coordinate ring. -/
theorem projectiveWeierstrassSpecialFibreIdeal_eq_scalar_span
    (W : WeierstrassCurve ℤ_[2]) :
    projectiveWeierstrassSpecialFibreIdeal W =
      Ideal.span {algebraMap ℤ_[2]
        (projectiveWeierstrassCoordinateRing W) 2} := by
  simp only [projectiveWeierstrassSpecialFibreIdeal, Ideal.map_span,
    Set.image_singleton]
  rfl

/-- The canonical split cubic has a point on the `Z` basic open:
the coordinate `Z` survives in its homogeneous coordinate ring. -/
theorem splitNodeProjectiveCoordinate_Z_ne_zero :
    (Ideal.Quotient.mk (Ideal.span {splitNodeProjectiveCubic}))
      (MvPolynomial.X (2 : Fin 3)) ≠ 0 := by
  let S := MvPolynomial (Fin 3) (ZMod 2)
  let I : Ideal S := Ideal.span {splitNodeProjectiveCubic}
  let e : S →+* ZMod 2 :=
    MvPolynomial.eval₂Hom (RingHom.id (ZMod 2)) ![0, 0, 1]
  have hX0 : e (MvPolynomial.X (0 : Fin 3)) = 0 :=
    MvPolynomial.eval₂Hom_X' _ _ _
  have hX1 : e (MvPolynomial.X (1 : Fin 3)) = 0 :=
    MvPolynomial.eval₂Hom_X' _ _ _
  have hX2 : e (MvPolynomial.X (2 : Fin 3)) = 1 :=
    MvPolynomial.eval₂Hom_X' _ _ _
  have hF : e splitNodeProjectiveCubic = 0 := by
    simp only [splitNodeProjectiveCubic, map_sub, map_add,
      map_mul, map_pow, hX0, hX1, hX2]
    ring
  have hI : I ≤ RingHom.ker e := by
    apply Ideal.span_le.mpr
    intro p hp
    rcases Set.mem_singleton_iff.mp hp with rfl
    exact hF
  intro hz
  have hz' : e (MvPolynomial.X (2 : Fin 3)) = 0 :=
    hI (Ideal.Quotient.eq_zero_iff_mem.mp hz)
  exact one_ne_zero (hX2.symm.trans hz')

/-- The graded translation fixes the projective `Z` coordinate. -/
theorem projectivePlaneTranslation_Z
    (R : Type*) [CommRing R] (a b : R) :
    (projectivePlaneTranslation R a b)
      (MvPolynomial.X (2 : Fin 3)) = MvPolynomial.X 2 := by
  change (MvPolynomial.eval₂Hom MvPolynomial.C
    ![MvPolynomial.X 0 + MvPolynomial.C a * MvPolynomial.X 2,
      MvPolynomial.X 1 + MvPolynomial.C b * MvPolynomial.X 2,
      MvPolynomial.X 2])
      (MvPolynomial.X (2 : Fin 3)) = MvPolynomial.X 2
  exact MvPolynomial.eval₂Hom_X' _ _ _

/-- Under the split hypotheses the integral equation's reduced
`Z` coordinate also survives. -/
theorem splitNode_projectiveSpecialFibreCoordinate_Z_ne_zero
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W))
      ((Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
        (MvPolynomial.X (2 : Fin 3))) ≠ 0 := by
  intro hz
  have he := congrArg
    (splitNode_projectiveSpecialFibreCoordinateRing_equiv W hnode hsplit) hz
  rw [splitNode_projectiveSpecialFibreCoordinateRing_equiv_apply] at he
  have he' :
      (Ideal.Quotient.mk (Ideal.span {splitNodeProjectiveCubic}))
        (MvPolynomial.X (2 : Fin 3)) = 0 := by
    simpa only [MvPolynomial.map_X, projectivePlaneTranslation_Z, map_zero]
      using he
  exact splitNodeProjectiveCoordinate_Z_ne_zero he'

/-- The integral degree-zero `Y` chart modulo the base uniformizer
is isomorphic to the corresponding chart of the graded quotient.
The nonvanishing power condition follows from the split nodal
quotient's domain property. -/
noncomputable def splitNodeProjectiveYChartQuotientEquiv
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
      projectiveWeierstrassQuotientGrading W
    letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
      projectiveWeierstrassSpecialFibreGrading W
    let y := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
      (MvPolynomial.X (1 : Fin 3))
    (HomogeneousLocalization.Away
      (projectiveWeierstrassQuotientComponent W) y ⧸
      Ideal.span {homogeneousScalarAway
        (projectiveWeierstrassQuotientComponent W) y 2}) ≃+*
      HomogeneousLocalization.Away
        (projectiveWeierstrassSpecialFibreComponent W)
        (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W) y) := by
  letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
    projectiveWeierstrassQuotientGrading W
  letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
    projectiveWeierstrassSpecialFibreGrading W
  let y := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
    (MvPolynomial.X (1 : Fin 3))
  haveI : IsDomain (projectiveWeierstrassCoordinateRing W ⧸
      projectiveWeierstrassSpecialFibreIdeal W) := by
    have e := splitNode_projectiveSpecialFibreCoordinateRing_equiv W hnode hsplit
    haveI : IsDomain (MvPolynomial (Fin 3) (ZMod 2) ⧸
        Ideal.span {splitNodeProjectiveCubic}) :=
      splitNodeProjectiveCoordinateRing_isDomain
    exact e.toMulEquiv.isDomain _
  have hy : y ∈ projectiveWeierstrassQuotientComponent W 1 :=
    projectiveWeierstrassCoordinate_mem_degree_one W 1
  have hyne :
      (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W)) y ≠ 0 := by
    intro hz
    exact projectiveWeierstrassSpecialFibreIdeal_not_Y W
      (Ideal.Quotient.eq_zero_iff_mem.mp hz)
  exact homogeneousQuotientAwayRingEquiv
    (projectiveWeierstrassQuotientComponent W)
    (projectiveWeierstrassSpecialFibreIdeal W)
    (projectiveWeierstrassSpecialFibreIdeal_isHomogeneous W)
    2 (projectiveWeierstrassSpecialFibreIdeal_eq_scalar_span W)
    y 1 hy (fun n => pow_ne_zero n hyne)

/-- The same quotient-versus-localization comparison for `Z`.
It is the second chart of the integral two-open cover. -/
noncomputable def splitNodeProjectiveZChartQuotientEquiv
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
      projectiveWeierstrassQuotientGrading W
    letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
      projectiveWeierstrassSpecialFibreGrading W
    let z := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
      (MvPolynomial.X (2 : Fin 3))
    (HomogeneousLocalization.Away
      (projectiveWeierstrassQuotientComponent W) z ⧸
      Ideal.span {homogeneousScalarAway
        (projectiveWeierstrassQuotientComponent W) z 2}) ≃+*
      HomogeneousLocalization.Away
        (projectiveWeierstrassSpecialFibreComponent W)
        (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W) z) := by
  letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
    projectiveWeierstrassQuotientGrading W
  letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
    projectiveWeierstrassSpecialFibreGrading W
  let z := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
    (MvPolynomial.X (2 : Fin 3))
  haveI : IsDomain (projectiveWeierstrassCoordinateRing W ⧸
      projectiveWeierstrassSpecialFibreIdeal W) := by
    have e := splitNode_projectiveSpecialFibreCoordinateRing_equiv W hnode hsplit
    haveI : IsDomain (MvPolynomial (Fin 3) (ZMod 2) ⧸
        Ideal.span {splitNodeProjectiveCubic}) :=
      splitNodeProjectiveCoordinateRing_isDomain
    exact e.toMulEquiv.isDomain _
  have hz : z ∈ projectiveWeierstrassQuotientComponent W 1 :=
    projectiveWeierstrassCoordinate_mem_degree_one W 2
  have hzne :
      (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W)) z ≠ 0 :=
    splitNode_projectiveSpecialFibreCoordinate_Z_ne_zero W hnode hsplit
  exact homogeneousQuotientAwayRingEquiv
    (projectiveWeierstrassQuotientComponent W)
    (projectiveWeierstrassSpecialFibreIdeal W)
    (projectiveWeierstrassSpecialFibreIdeal_isHomogeneous W)
    2 (projectiveWeierstrassSpecialFibreIdeal_eq_scalar_span W)
    z 1 hz (fun n => pow_ne_zero n hzne)

/-- The analogous quotient-ring comparison on the `Z ∩ Y`
overlap, represented by the homogeneous product `Z * Y` of degree
two. It has the same base-uniformizer kernel. -/
noncomputable def splitNodeProjectiveZYChartQuotientEquiv
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
      projectiveWeierstrassQuotientGrading W
    letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
      projectiveWeierstrassSpecialFibreGrading W
    let z := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
      (MvPolynomial.X (2 : Fin 3))
    let y := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
      (MvPolynomial.X (1 : Fin 3))
    (HomogeneousLocalization.Away
      (projectiveWeierstrassQuotientComponent W) (z * y) ⧸
      Ideal.span {homogeneousScalarAway
        (projectiveWeierstrassQuotientComponent W) (z * y) 2}) ≃+*
      HomogeneousLocalization.Away
        (projectiveWeierstrassSpecialFibreComponent W)
        (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W) (z * y)) := by
  letI : GradedAlgebra (projectiveWeierstrassQuotientComponent W) :=
    projectiveWeierstrassQuotientGrading W
  letI : GradedAlgebra (projectiveWeierstrassSpecialFibreComponent W) :=
    projectiveWeierstrassSpecialFibreGrading W
  let z := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
    (MvPolynomial.X (2 : Fin 3))
  let y := (Ideal.Quotient.mk (Ideal.span {projectiveWeierstrassCubic W}))
    (MvPolynomial.X (1 : Fin 3))
  haveI : IsDomain (projectiveWeierstrassCoordinateRing W ⧸
      projectiveWeierstrassSpecialFibreIdeal W) := by
    have e := splitNode_projectiveSpecialFibreCoordinateRing_equiv W hnode hsplit
    haveI : IsDomain (MvPolynomial (Fin 3) (ZMod 2) ⧸
        Ideal.span {splitNodeProjectiveCubic}) :=
      splitNodeProjectiveCoordinateRing_isDomain
    exact e.toMulEquiv.isDomain _
  have hz : z ∈ projectiveWeierstrassQuotientComponent W 1 :=
    projectiveWeierstrassCoordinate_mem_degree_one W 2
  have hy : y ∈ projectiveWeierstrassQuotientComponent W 1 :=
    projectiveWeierstrassCoordinate_mem_degree_one W 1
  have hzne :
      (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W)) z ≠ 0 :=
    splitNode_projectiveSpecialFibreCoordinate_Z_ne_zero W hnode hsplit
  have hyne :
      (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W)) y ≠ 0 := by
    intro h
    exact projectiveWeierstrassSpecialFibreIdeal_not_Y W
      (Ideal.Quotient.eq_zero_iff_mem.mp h)
  have hzyne :
      (Ideal.Quotient.mk (projectiveWeierstrassSpecialFibreIdeal W)) (z * y) ≠ 0 := by
    rw [map_mul]
    exact mul_ne_zero hzne hyne
  exact homogeneousQuotientAwayRingEquiv
    (projectiveWeierstrassQuotientComponent W)
    (projectiveWeierstrassSpecialFibreIdeal W)
    (projectiveWeierstrassSpecialFibreIdeal_isHomogeneous W)
    2 (projectiveWeierstrassSpecialFibreIdeal_eq_scalar_span W)
    (z * y) 2 (SetLike.GradedMul.mul_mem hz hy)
    (fun n => pow_ne_zero n hzyne)

end Beal.General