import Beal.«Beal.General».ZChartSpecialFibreHeight

/-!
Lifting a principal special-fibre maximal ideal to two parameters
in the integral local ring. The principal-special-fibre premise
must be proved separately at every non-node prime.
-/

namespace Beal.General

/-- An ideal containing `a` is generated by `a` and `t` if its
image modulo `a` is generated by the image of `t`. This is an
exact ideal correspondence, with no rational-point assumption. -/
theorem ideal_eq_span_pair_of_principal_reduction
    {A : Type*} [CommRing A] (M : Ideal A) (a t : A)
    (ha : a ∈ M)
    (hred : Ideal.map (Ideal.Quotient.mk (Ideal.span {a})) M =
      Ideal.span {(Ideal.Quotient.mk (Ideal.span {a})) t}) :
    M = Ideal.span {a, t} := by
  let I : Ideal A := Ideal.span {a}
  let q : A →+* A ⧸ I := Ideal.Quotient.mk I
  have hI : I ≤ M := (Ideal.span_singleton_le_iff_mem M).mpr ha
  have hmap : Ideal.map q M =
      Ideal.map q (Ideal.span {t}) := by
    rw [hred, Ideal.map_span]
    simp only [Set.image_singleton]
  have hc := congrArg (Ideal.comap q) hmap
  have hker : RingHom.ker q = I := Ideal.mk_ker
  have hsup : M ⊔ I = Ideal.span {t} ⊔ I := by
    simpa only [Ideal.comap_map_of_surjective q
      Ideal.Quotient.mk_surjective,
      ← RingHom.ker_eq_comap_bot, hker] using hc
  calc
    M = M ⊔ I := (sup_eq_left.mpr hI).symm
    _ = Ideal.span {t} ⊔ I := hsup
    _ = I ⊔ Ideal.span {t} := sup_comm _ _
    _ = Ideal.span {a, t} := (Ideal.span_insert a {t}).symm

/-- At a strict specialization of the split special fibre,
principality of the maximal ideal modulo the image of `2`
would supply both parameters and dimension two in the *actual*
integral chart. The unproved premise is precisely the missing
arbitrary-degree smooth-curve local parameter. -/
theorem splitNode_ZChart_dim_two_of_principal_reduction
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0)
    (Q : Ideal (projectiveWeierstrassZChartRing W)) [Q.IsPrime]
    (hPQ : (Ideal.span {(Ideal.Quotient.mk
      (Ideal.span {localSurfaceEquation W 0 0}))
        (MvPolynomial.C (2 : ℤ_[2]))} :
        Ideal (projectiveWeierstrassZChartRing W)) < Q)
    (t : Localization.AtPrime Q)
    (hred : let L := Localization.AtPrime Q
      let a : L := (algebraMap (projectiveWeierstrassZChartRing W) L)
        ((Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0}))
          (MvPolynomial.C (2 : ℤ_[2])))
      Ideal.map (Ideal.Quotient.mk (Ideal.span {a}))
        (LocalRing.maximalIdeal L) =
        Ideal.span {(Ideal.Quotient.mk (Ideal.span {a})) t}) :
    let L := Localization.AtPrime Q
    let a : L := (algebraMap (projectiveWeierstrassZChartRing W) L)
      ((Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0}))
        (MvPolynomial.C (2 : ℤ_[2])))
    IsNoetherianRing L ∧ ringKrullDim L = 2 ∧
      LocalRing.maximalIdeal L = Ideal.span {a, t} := by
  let R := projectiveWeierstrassZChartRing W
  let L := Localization.AtPrime Q
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let f : R →+* L := algebraMap R L
  let a : L := f (q (MvPolynomial.C (2 : ℤ_[2])))
  have h2 : q (MvPolynomial.C (2 : ℤ_[2])) ∈ Q :=
    hPQ.le (Ideal.mem_span_singleton_self _)
  have ha : a ∈ LocalRing.maximalIdeal L := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal (I := Q)]
    exact Ideal.mem_map_of_mem f h2
  have hmax : LocalRing.maximalIdeal L = Ideal.span {a, t} :=
    ideal_eq_span_pair_of_principal_reduction
      (LocalRing.maximalIdeal L) a t ha hred
  haveI : IsNoetherianRing L :=
    projectiveWeierstrassZChart_atPrime_isNoetherian W Q
  exact ⟨inferInstance,
    splitNode_ZChart_strictSpecialFibrePrime_dim_two_of_pair
      W hnode hsplit Q hPQ a t hmax, hmax⟩

end Beal.General