import Beal.«Beal.General».ZChartFlatness
import Mathlib.Algebra.MvPolynomial.PDeriv

/-!
Dimension lower bounds at primes above the nodal special fibre.
Strict specializations of its generic prime need a two-step chain
before a two-parameter certificate can establish regularity.
The statements apply to arbitrary primes, not just rational points.
-/

namespace Beal.General

/-- Translation preserves the special-fibre prime of the actual
`Z = 1` ring: it is always the ideal generated by the image of
the base uniformizer, independently of nodal hypotheses. -/
theorem projectiveWeierstrassZChart_shiftSpecialFibre_eq_span_two
    (W : WeierstrassCurve ℤ_[2]) (x y : ℤ_[2]) :
    projectiveWeierstrassZChart_shiftPrime W x y
      (localSurfaceSpecialFibreIdeal W x y) =
    Ideal.span {(Ideal.Quotient.mk
      (Ideal.span {localSurfaceEquation W 0 0}))
        (MvPolynomial.C (2 : ℤ_[2]))} := by
  let R := projectiveWeierstrassZChartRing W
  let T := localSurfaceCoordinateRing W x y
  let e : R ≃ₐ[ℤ_[2]] T :=
    projectiveWeierstrassZChart_shiftEquiv W x y
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let q' : MvPolynomial (Fin 2) ℤ_[2] →+* T :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W x y})
  let t : R := q (MvPolynomial.C (2 : ℤ_[2]))
  let t' : T := q' (MvPolynomial.C (2 : ℤ_[2]))
  have hbase : e t = t' := by
    change e (algebraMap ℤ_[2] R 2) = algebraMap ℤ_[2] T 2
    exact e.commutes 2
  change (localSurfaceSpecialFibreIdeal W x y).comap
    (e.toRingEquiv : R →+* T) = Ideal.span {t}
  calc
    (localSurfaceSpecialFibreIdeal W x y).comap
        (e.toRingEquiv : R →+* T) =
      Ideal.map (e.toRingEquiv.symm : T →+* R)
        (localSurfaceSpecialFibreIdeal W x y) :=
      (Ideal.map_symm _ e.toRingEquiv).symm
    _ = Ideal.span {t} := by
      rw [localSurfaceSpecialFibreIdeal_eq_span_two, Ideal.map_span]
      simp only [Set.image_singleton]
      have ht : e.symm t' = t := by rw [← hbase, e.symm_apply_apply]
      change Ideal.span {e.symm t'} = Ideal.span {t}
      rw [ht]

/-- The `v` partial of the full reduced cubic is `u`, not a
derivative of the two-line tangent cone. -/
theorem splitNodeCubic_pderiv_v :
    MvPolynomial.pderiv (1 : Fin 2) splitNodeCubic =
      (MvPolynomial.X 0 : MvPolynomial (Fin 2) (ZMod 2)) := by
  simp [splitNodeCubic, MvPolynomial.pderiv_X_self,
    MvPolynomial.pderiv_X_of_ne]
  have htwo : (2 : MvPolynomial (Fin 2) (ZMod 2)) = 0 := by
    change MvPolynomial.C (2 : ZMod 2) = 0
    rw [show (2 : ZMod 2) = 0 by decide, map_zero]
  linear_combination (MvPolynomial.X (1 : Fin 2) :
    MvPolynomial (Fin 2) (ZMod 2)) * htwo

/-- The `u` partial of the full reduced cubic in characteristic two. -/
theorem splitNodeCubic_pderiv_u :
    MvPolynomial.pderiv (0 : Fin 2) splitNodeCubic =
      (MvPolynomial.X 1 + MvPolynomial.X 0 ^ 2 :
        MvPolynomial (Fin 2) (ZMod 2)) := by
  simp [splitNodeCubic, MvPolynomial.pderiv_X_self,
    MvPolynomial.pderiv_X_of_ne]
  have htwo : (2 : MvPolynomial (Fin 2) (ZMod 2)) = 0 := by
    change MvPolynomial.C (2 : ZMod 2) = 0
    rw [show (2 : ZMod 2) = 0 by decide, map_zero]
  linear_combination -(2 * (MvPolynomial.X (0 : Fin 2) :
    MvPolynomial (Fin 2) (ZMod 2)) ^ 2) * htwo

/-- No ideal away from the affine node can contain both partials
of the full split nodal cubic. This is a Jacobian *certificate*,
not a regular-local-ring criterion for the integral chart. -/
theorem splitNodeCubic_partials_only_at_origin
    (J : Ideal (MvPolynomial (Fin 2) (ZMod 2)))
    (hu : MvPolynomial.pderiv (0 : Fin 2) splitNodeCubic ∈ J)
    (hv : MvPolynomial.pderiv (1 : Fin 2) splitNodeCubic ∈ J) :
    MvPolynomial.X (0 : Fin 2) ∈ J ∧
      MvPolynomial.X (1 : Fin 2) ∈ J := by
  have hX0 : MvPolynomial.X (0 : Fin 2) ∈ J := by
    simpa only [splitNodeCubic_pderiv_v] using hv
  have hsum : (MvPolynomial.X 1 + MvPolynomial.X 0 ^ 2 :
      MvPolynomial (Fin 2) (ZMod 2)) ∈ J := by
    simpa only [splitNodeCubic_pderiv_u] using hu
  have hX1 : MvPolynomial.X (1 : Fin 2) ∈ J := by
    have hp : (MvPolynomial.X (0 : Fin 2) :
        MvPolynomial (Fin 2) (ZMod 2)) ^ 2 ∈ J := by
      simpa only [pow_two] using J.mul_mem_left
        (MvPolynomial.X (0 : Fin 2)) hX0
    have hd := J.sub_mem hsum hp
    convert hd using 1
    ring
  exact ⟨hX0, hX1⟩

/-- In the coordinate ring of the *full* reduced affine cubic,
any ideal containing both partials also contains the node ideal.
This holds for arbitrary ideals, including those of non-rational
closed points; it does not itself prove total-space regularity. -/
theorem splitNodeCubic_quotient_partials_only_at_node
    (J : Ideal (MvPolynomial (Fin 2) (ZMod 2) ⧸
      Ideal.span {splitNodeCubic}))
    (hu : (Ideal.Quotient.mk (Ideal.span {splitNodeCubic}))
      (MvPolynomial.pderiv (0 : Fin 2) splitNodeCubic) ∈ J)
    (hv : (Ideal.Quotient.mk (Ideal.span {splitNodeCubic}))
      (MvPolynomial.pderiv (1 : Fin 2) splitNodeCubic) ∈ J) :
    splitNode_originIdeal ≤ J := by
  let S := MvPolynomial (Fin 2) (ZMod 2)
  let I : Ideal S := Ideal.span {splitNodeCubic}
  let q : S →+* S ⧸ I := Ideal.Quotient.mk I
  have hxy := splitNodeCubic_partials_only_at_origin
    (J.comap q) hu hv
  change Ideal.span {q (MvPolynomial.X (0 : Fin 2)),
    q (MvPolynomial.X (1 : Fin 2))} ≤ J
  apply Ideal.span_le.mpr
  intro a ha
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
  rcases ha with rfl | rfl
  · exact hxy.1
  · exact hxy.2

/-- Every prime of the reduced nodal cubic that contains `u`
also contains `v`: reducing the full equation modulo `u`
gives `v² = 0`. This includes non-rational primes. -/
theorem splitNodeCubic_prime_contains_u_implies_node
    (J : Ideal (MvPolynomial (Fin 2) (ZMod 2) ⧸
      Ideal.span {splitNodeCubic})) [J.IsPrime]
    (hu : (Ideal.Quotient.mk (Ideal.span {splitNodeCubic}))
      (MvPolynomial.X (0 : Fin 2)) ∈ J) :
    splitNode_originIdeal ≤ J := by
  let S := MvPolynomial (Fin 2) (ZMod 2)
  let I : Ideal S := Ideal.span {splitNodeCubic}
  let q : S →+* S ⧸ I := Ideal.Quotient.mk I
  let K : Ideal S := J.comap q
  haveI : K.IsPrime := Ideal.comap_isPrime q J
  have hF : splitNodeCubic ∈ K := by
    change q splitNodeCubic ∈ J
    have hz : q splitNodeCubic = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.mpr
        (Ideal.subset_span (Set.mem_singleton _))
    rw [hz]
    exact J.zero_mem
  have hu' : MvPolynomial.X (0 : Fin 2) ∈ K := hu
  have hVU : (MvPolynomial.X (1 : Fin 2) *
      MvPolynomial.X (0 : Fin 2) : S) ∈ K :=
    K.mul_mem_left _ hu'
  have hu3 : (MvPolynomial.X (0 : Fin 2) : S) ^ 3 ∈ K := by
    convert K.mul_mem_left
      ((MvPolynomial.X (0 : Fin 2) : S) ^ 2) hu' using 1
  have hv2 : (MvPolynomial.X (1 : Fin 2) : S) ^ 2 ∈ K := by
    have heq : (MvPolynomial.X (1 : Fin 2) : S) ^ 2 =
        splitNodeCubic - MvPolynomial.X 1 * MvPolynomial.X 0 +
          MvPolynomial.X 0 ^ 3 := by
      dsimp [splitNodeCubic]
      ring
    rw [heq]
    exact K.add_mem (K.sub_mem hF hVU) hu3
  have hv : MvPolynomial.X (1 : Fin 2) ∈ K :=
    (‹K.IsPrime›).mem_of_pow_mem 2 hv2
  change Ideal.span {q (MvPolynomial.X (0 : Fin 2)),
    q (MvPolynomial.X (1 : Fin 2))} ≤ J
  apply Ideal.span_le.mpr
  intro a ha
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
  rcases ha with rfl | rfl
  · exact hu'
  · exact hv

/-- Away from the node, the same `v` partial is outside every
special-fibre prime. Its image is therefore a unit in each such
localization; this does not yet supply a regular-parameter proof
for the integral chart. -/
theorem splitNodeCubic_pderiv_v_avoids_nonNode_prime
    (J : Ideal (MvPolynomial (Fin 2) (ZMod 2) ⧸
      Ideal.span {splitNodeCubic})) [J.IsPrime]
    (hJ : ¬ splitNode_originIdeal ≤ J) :
    (Ideal.Quotient.mk (Ideal.span {splitNodeCubic}))
      (MvPolynomial.pderiv (1 : Fin 2) splitNodeCubic) ∉ J := by
  intro hv
  apply hJ
  apply splitNodeCubic_prime_contains_u_implies_node J
  simpa only [splitNodeCubic_pderiv_v] using hv

private theorem exists_prime_below_of_height_ge_one
    {A : Type*} [CommRing A]
    (M : PrimeSpectrum A) (hM : (1 : ℕ∞) ≤ Order.height M) :
    ∃ J : PrimeSpectrum A, J < M := by
  by_contra hn
  have hzero : Order.height M ≤ 0 := by
    apply Order.height_le
    intro s hs
    by_contra hlen
    have hlen' : s.length ≠ 0 := by
      intro hz
      simp [hz] at hlen
    have hlt : s.eraseLast.last < M := by
      simpa only [hs] using s.eraseLast_last_rel_last hlen'
    exact hn ⟨s.eraseLast.last, hlt⟩
  have hbad : (1 : ℕ∞) ≤ 0 := hM.trans hzero
  norm_num at hbad

/-- The generic point of the split nodal special fibre has a
prime strictly below it in the translated integral surface.
This makes the dimension-one certificate usable in longer
specialization chains. -/
theorem splitNode_specialFibreGeneric_has_lower_prime
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let R := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
    let P := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
    letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
      (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
    ∃ J : Ideal R, J.IsPrime ∧ J < P := by
  let R := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let P : Ideal R :=
    localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  let L := Localization.AtPrime P
  let M : PrimeSpectrum L :=
    ⟨LocalRing.maximalIdeal L, (LocalRing.maximalIdeal.isMaximal L).isPrime⟩
  obtain ⟨K, hK⟩ := exists_prime_below_of_height_ge_one M
    (splitNode_specialFibreGeneric_height_ge_one W hnode hsplit)
  let f : R →+* L := algebraMap R L
  let J : Ideal R := K.asIdeal.comap f
  have hJprime : J.IsPrime := Ideal.comap_isPrime f K.asIdeal
  have hJP : J < P := by
    have h := (IsLocalization.AtPrime.orderIsoOfPrime L P).strictMono
      (show (⟨K.asIdeal, K.isPrime⟩ :
        { p : Ideal L // p.IsPrime }) <
        ⟨M.asIdeal, M.isPrime⟩ from hK)
    change J < (LocalRing.maximalIdeal L).comap f at h
    rw [Localization.AtPrime.comap_maximalIdeal] at h
    exact h
  exact ⟨J, hJprime, hJP⟩

/-- Any strict specialization of the generic special-fibre prime
has local dimension at least two, in the translated surface.
No maximal-ideal generator statement is asserted here. -/
theorem splitNode_specialFibre_strictPrime_height_ge_two
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0)
    (Q : Ideal (localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)))
    [Q.IsPrime]
    (hPQ : localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄) < Q) :
    (2 : ℕ∞) ≤ Order.height
      (⟨LocalRing.maximalIdeal (Localization.AtPrime Q),
        (LocalRing.maximalIdeal.isMaximal _).isPrime⟩ :
        PrimeSpectrum (Localization.AtPrime Q)) := by
  let R := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let P : Ideal R :=
    localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  obtain ⟨J, hJ, hJP⟩ :=
    splitNode_specialFibreGeneric_has_lower_prime W hnode hsplit
  let S₀ : PrimeSpectrum R := ⟨J, hJ⟩
  let S₁ : PrimeSpectrum R := ⟨P, ‹P.IsPrime›⟩
  let S₂ : PrimeSpectrum R := ⟨Q, ‹Q.IsPrime›⟩
  let chain : LTSeries (PrimeSpectrum R) :=
    ((RelSeries.singleton (· < ·) S₀).snoc S₁ hJP).snoc S₂ hPQ
  have hheight : (2 : ℕ∞) ≤ Order.height S₂ := by
    simpa [chain] using (Order.length_le_height_last (p := chain))
  exact hheight.trans (by simpa [S₂] using height_le_atPrime_maximal_height Q)

/-- The same dimension lower bound in the actual integral `Z = 1`
chart, at every prime strictly above the translated generic
special-fibre prime. -/
theorem splitNode_ZChart_strictSpecialFibrePrime_height_ge_two
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0)
    (Q : Ideal (projectiveWeierstrassZChartRing W)) [Q.IsPrime]
    (hPQ : (Ideal.span {(Ideal.Quotient.mk
      (Ideal.span {localSurfaceEquation W 0 0}))
        (MvPolynomial.C (2 : ℤ_[2]))} :
        Ideal (projectiveWeierstrassZChartRing W)) < Q) :
    (2 : ℕ∞) ≤ Order.height
      (⟨LocalRing.maximalIdeal (Localization.AtPrime Q),
        (LocalRing.maximalIdeal.isMaximal _).isPrime⟩ :
        PrimeSpectrum (Localization.AtPrime Q)) := by
  let R := projectiveWeierstrassZChartRing W
  let T := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let e : R ≃ₐ[ℤ_[2]] T :=
    projectiveWeierstrassZChart_shiftEquiv W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let P : Ideal T :=
    localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  have hPQ' : P.comap e.toRingEquiv.toRingHom < Q := by
    change projectiveWeierstrassZChart_shiftPrime W W.a₃
      (W.a₃ ^ 2 + W.a₄)
        (localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)) < Q
    rw [projectiveWeierstrassZChart_shiftSpecialFibre_eq_span_two]
    exact hPQ
  obtain ⟨J, hJ, hJP⟩ :=
    splitNode_specialFibreGeneric_has_lower_prime W hnode hsplit
  have hJ' : (J.comap e.toRingEquiv.toRingHom).IsPrime :=
    Ideal.comap_isPrime e.toRingEquiv.toRingHom J
  have hP' : (P.comap e.toRingEquiv.toRingHom).IsPrime :=
    Ideal.comap_isPrime e.toRingEquiv.toRingHom P
  have hlt : J.comap e.toRingEquiv.toRingHom <
      P.comap e.toRingEquiv.toRingHom := by
    apply lt_of_le_of_ne (Ideal.comap_mono hJP.le)
    intro he
    exact (ne_of_lt hJP)
      ((Ideal.comap_injective_of_surjective e.toRingEquiv.toRingHom
        e.surjective) he)
  let S₀ : PrimeSpectrum R :=
    ⟨J.comap e.toRingEquiv.toRingHom, hJ'⟩
  let S₁ : PrimeSpectrum R :=
    ⟨P.comap e.toRingEquiv.toRingHom, hP'⟩
  let S₂ : PrimeSpectrum R := ⟨Q, ‹Q.IsPrime›⟩
  let chain : LTSeries (PrimeSpectrum R) :=
    ((RelSeries.singleton (· < ·) S₀).snoc S₁ hlt).snoc S₂ hPQ'
  have hheight : (2 : ℕ∞) ≤ Order.height S₂ := by
    simpa [chain] using (Order.length_le_height_last (p := chain))
  exact hheight.trans (by simpa [S₂] using height_le_atPrime_maximal_height Q)

/-- Once a maximal ideal at a strict specialization of `(2)` has
two generators, the existing local height bound gives dimension
exactly two. This deliberately leaves the required generator
construction at non-node primes as a separate obligation. -/
theorem splitNode_ZChart_strictSpecialFibrePrime_dim_two_of_pair
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0)
    (Q : Ideal (projectiveWeierstrassZChartRing W)) [Q.IsPrime]
    (hPQ : (Ideal.span {(Ideal.Quotient.mk
      (Ideal.span {localSurfaceEquation W 0 0}))
        (MvPolynomial.C (2 : ℤ_[2]))} :
        Ideal (projectiveWeierstrassZChartRing W)) < Q)
    (a b : Localization.AtPrime Q)
    (hmax : LocalRing.maximalIdeal (Localization.AtPrime Q) =
      Ideal.span {a, b}) :
    ringKrullDim (Localization.AtPrime Q) = 2 := by
  let L := Localization.AtPrime Q
  let M : PrimeSpectrum L :=
    ⟨LocalRing.maximalIdeal L, (LocalRing.maximalIdeal.isMaximal L).isPrime⟩
  haveI : IsNoetherianRing L :=
    projectiveWeierstrassZChart_atPrime_isNoetherian W Q
  have hmin : LocalRing.maximalIdeal L ∈
      (Ideal.span {a, b}).minimalPrimes := by
    rw [← hmax]
    exact ⟨⟨(LocalRing.maximalIdeal.isMaximal L).isPrime, le_rfl⟩,
      fun J hJ _ => hJ.2⟩
  have hheight : Order.height M = 2 :=
    le_antisymm (local_pair_minimal_height_le_two a b hmin)
      (splitNode_ZChart_strictSpecialFibrePrime_height_ge_two
        W hnode hsplit Q hPQ)
  have hDim : ringKrullDim L = (↑(Order.height M) : WithBot ℕ∞) := by
    change Order.krullDim (PrimeSpectrum L) =
      (↑(Order.height M) : WithBot ℕ∞)
    rw [Order.krullDim_eq_iSup_height]
    apply le_antisymm
    · apply iSup_le
      intro S
      exact WithBot.coe_le_coe.mpr
        (Order.height_mono (show S ≤ M from
          LocalRing.le_maximalIdeal S.isPrime.ne_top))
    · exact le_iSup_of_le M le_rfl
  simpa only [hheight] using hDim

end Beal.General