import Beal.«Beal.General».TranslatedZChartNode

/-!
The uniformizer in the actual integral `Z = 1` chart.
This transfers the translated-surface certificate through the
integral coordinate change, rather than working only modulo `2`.
-/

namespace Beal.General

/-- Every prime localization of the actual `Z = 1` coordinate
ring is Noetherian. This does not assert regularity. -/
theorem projectiveWeierstrassZChart_atPrime_isNoetherian
    (W : WeierstrassCurve ℤ_[2])
    (P : Ideal (projectiveWeierstrassZChartRing W)) [P.IsPrime] :
    IsNoetherianRing (Localization.AtPrime P) := by
  let S := MvPolynomial (Fin 2) ℤ_[2]
  let R := projectiveWeierstrassZChartRing W
  let q : S →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  haveI : IsNoetherianRing R :=
    isNoetherianRing_of_surjective S R q Ideal.Quotient.mk_surjective
  exact IsLocalization.isNoetherianRing P.primeCompl _ inferInstance

/-- The base uniformizer is a non-zero-divisor in the *actual*
integral `Z = 1` chart, under the nodal split-fibre hypotheses.
This is a flatness certificate, not an all-stalk regularity theorem. -/
theorem splitNode_ZChart_surfaceTwo_regular
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let R := projectiveWeierstrassZChartRing W
    let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
      Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
    ∀ a : R, q (MvPolynomial.C (2 : ℤ_[2])) * a = 0 → a = 0 := by
  let R := projectiveWeierstrassZChartRing W
  let T := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let e : R ≃ₐ[ℤ_[2]] T :=
    projectiveWeierstrassZChart_shiftEquiv W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let q' : MvPolynomial (Fin 2) ℤ_[2] →+* T :=
    Ideal.Quotient.mk (Ideal.span
      {localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)})
  have hbase : e (q (MvPolynomial.C (2 : ℤ_[2]))) =
      q' (MvPolynomial.C (2 : ℤ_[2])) := by
    change e (algebraMap ℤ_[2] R 2) = algebraMap ℤ_[2] T 2
    exact e.commutes 2
  change ∀ a : R, q (MvPolynomial.C (2 : ℤ_[2])) * a = 0 → a = 0
  intro a ha
  apply e.injective
  have hzero : q' (MvPolynomial.C (2 : ℤ_[2])) * e a = 0 := by
    rw [← hbase, ← map_mul, ha, map_zero]
  simpa only [map_zero] using
    (splitNode_surfaceTwo_regular W hnode hsplit (e a) hzero)

/-- The image of `2` remains a non-zero-divisor in every prime
localization of the actual `Z = 1` ring, including primes of the
special fibre away from the known node. -/
theorem splitNode_ZChart_surfaceTwo_regular_atPrime
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0)
    (P : Ideal (projectiveWeierstrassZChartRing W)) [P.IsPrime] :
    let R := projectiveWeierstrassZChartRing W
    let L := Localization.AtPrime P
    let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
      Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
    ∀ a : L,
      (algebraMap R L) (q (MvPolynomial.C (2 : ℤ_[2]))) * a = 0 → a = 0 := by
  let R := projectiveWeierstrassZChartRing W
  let L := Localization.AtPrime P
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let t : R := q (MvPolynomial.C (2 : ℤ_[2]))
  have ht : t ∈ nonZeroDivisors R := by
    rw [mem_nonZeroDivisors_iff]
    intro a ha
    exact splitNode_ZChart_surfaceTwo_regular W hnode hsplit a
      (by simpa only [mul_comm] using ha)
  have htL : (algebraMap R L) t ∈ nonZeroDivisors L :=
    IsLocalization.nonZeroDivisors_le_comap P.primeCompl L ht
  change ∀ a : L, (algebraMap R L) t * a = 0 → a = 0
  intro a ha
  exact (mem_nonZeroDivisors_iff.mp htL) a (by simpa only [mul_comm] using ha)

/-- The special fibre of the actual integral `Z = 1` chart is
integral: the prime is generated by the image of `2`.
This is the entire affine nodal cubic, not its tangent cone. -/
theorem splitNode_ZChart_specialFibrePrime
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let R := projectiveWeierstrassZChartRing W
    let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
      Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
    (Ideal.span {q (MvPolynomial.C (2 : ℤ_[2]))} : Ideal R).IsPrime := by
  let R := projectiveWeierstrassZChartRing W
  let T := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let e : R ≃ₐ[ℤ_[2]] T :=
    projectiveWeierstrassZChart_shiftEquiv W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let q' : MvPolynomial (Fin 2) ℤ_[2] →+* T :=
    Ideal.Quotient.mk (Ideal.span
      {localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)})
  let t : R := q (MvPolynomial.C (2 : ℤ_[2]))
  let t' : T := q' (MvPolynomial.C (2 : ℤ_[2]))
  have hbase : e t = t' := by
    change e (algebraMap ℤ_[2] R 2) = algebraMap ℤ_[2] T 2
    exact e.commutes 2
  have hTprime : (Ideal.span {t'} : Ideal T).IsPrime := by
    rw [← localSurfaceSpecialFibreIdeal_eq_span_two]
    exact (Ideal.Quotient.isDomain_iff_prime _).mp
      (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  haveI : (Ideal.span {t'} : Ideal T).IsPrime := hTprime
  have hmap : Ideal.map e.symm.toRingEquiv.toRingHom
      (Ideal.span {t'} : Ideal T) = Ideal.span {t} := by
    rw [Ideal.map_span]
    simp only [Set.image_singleton]
    have ht : e.symm t' = t := by rw [← hbase, e.symm_apply_apply]
    change Ideal.span {e.symm t'} = Ideal.span {t}
    rw [ht]
  have hp : (Ideal.map e.symm.toRingEquiv.toRingHom
      (Ideal.span {t'} : Ideal T)).IsPrime := by
    apply Ideal.map_isPrime_of_surjective e.symm.surjective
    intro z hz
    have hz' : e.symm z = 0 := RingHom.mem_ker.mp hz
    have : z = 0 := e.symm.injective (by simpa only [map_zero] using hz')
    rw [this]
    exact Ideal.zero_mem _
  change (Ideal.span {t} : Ideal R).IsPrime
  rwa [hmap] at hp

/-- The generic point of the nodal special fibre has positive
height in the translated surface. A minimal prime of the total
equation lies strictly below it: the ambient special-fibre
prime has an explicit two-step chain while the principal ideal
theorem bounds the minimal prime's height by one. -/
theorem splitNode_specialFibreGeneric_height_ge_one
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let P := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
    letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
      (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
    (1 : ℕ∞) ≤ Order.height
      (⟨LocalRing.maximalIdeal (Localization.AtPrime P),
        (LocalRing.maximalIdeal.isMaximal _).isPrime⟩ :
        PrimeSpectrum (Localization.AtPrime P)) := by
  let S := MvPolynomial (Fin 2) ℤ_[2]
  let F : S := localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let I : Ideal S := Ideal.span {F}
  let B : Ideal S := Ideal.span {MvPolynomial.C (2 : ℤ_[2])}
  let T := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let q : S →+* T := Ideal.Quotient.mk I
  let P : Ideal T := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  let Q : Ideal S := Ideal.comap q P
  haveI : Q.IsPrime := Ideal.comap_isPrime q P
  haveI : B.IsPrime := by
    change (Ideal.span {MvPolynomial.C (2 : ℤ_[2])} : Ideal S).IsPrime
    rw [← localSurfaceAmbient_reduction_kernel_eq_span_two]
    exact RingHom.ker_isPrime (MvPolynomial.map PadicInt.toZMod :
      S →+* MvPolynomial (Fin 2) (ZMod 2))
  have htP : q (MvPolynomial.C (2 : ℤ_[2])) ∈ P := by
    change q (MvPolynomial.C (2 : ℤ_[2])) ∈
      localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
    rw [localSurfaceSpecialFibreIdeal_eq_span_two]
    exact Ideal.mem_span_singleton_self _
  have hBQ : B ≤ Q :=
    (Ideal.span_singleton_le_iff_mem Q).mpr htP
  have hFQ : F ∈ Q := by
    change q F ∈ P
    have hz : q F = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.mpr
        (Ideal.subset_span (Set.mem_singleton _))
    rw [hz]
    exact P.zero_mem
  have hFnotB : F ∉ B := by
    change F ∉ (Ideal.span {MvPolynomial.C (2 : ℤ_[2])} : Ideal S)
    rw [← localSurfaceAmbient_reduction_kernel_eq_span_two]
    change MvPolynomial.map PadicInt.toZMod F ≠ 0
    rw [splitNode_surfaceEquation_modTwo W hnode hsplit]
    exact splitNodeCubic_ne_zero
  have hBQstrict : B < Q := by
    apply lt_of_le_of_ne hBQ
    intro he
    exact hFnotB (he ▸ hFQ)
  have hbotB : (⊥ : Ideal S) < B := by
    apply bot_lt_iff_ne_bot.mpr
    intro he
    have htwo : MvPolynomial.C (2 : ℤ_[2]) ∈ (⊥ : Ideal S) := by
      rw [← he]
      exact Ideal.mem_span_singleton_self _
    have hz : (2 : ℤ_[2]) = 0 :=
      (MvPolynomial.C_injective (Fin 2) ℤ_[2])
        (by simpa using Ideal.mem_bot.mp htwo)
    norm_num at hz
  let Q₀ : PrimeSpectrum S := ⟨⊥, Ideal.bot_prime⟩
  let Q₁ : PrimeSpectrum S := ⟨B, ‹B.IsPrime›⟩
  let Q₂ : PrimeSpectrum S := ⟨Q, ‹Q.IsPrime›⟩
  let s : LTSeries (PrimeSpectrum S) :=
    ((RelSeries.singleton (· < ·) Q₀).snoc Q₁ hbotB).snoc Q₂ hBQstrict
  have hQheight : (2 : ℕ∞) ≤ Order.height Q₂ := by
    simpa [s] using (Order.length_le_height_last (p := s))
  have hIQ : I ≤ Q := (Ideal.span_singleton_le_iff_mem Q).mpr hFQ
  obtain ⟨r, hr, hrQ⟩ := Ideal.exists_minimalPrimes_le hIQ
  haveI : r.IsPrime := hr.1.1
  have hrheight : Order.height (⟨r, hr.1.1⟩ : PrimeSpectrum S) ≤ 1 :=
    minimal_prime_over_principal_height_le_one_general F r hr
  have hrQstrict : r < Q := by
    apply lt_of_le_of_ne hrQ
    intro he
    have hbad : (2 : ℕ∞) ≤ 1 := by
      calc
        (2 : ℕ∞) ≤ Order.height Q₂ := hQheight
        _ = Order.height (⟨r, hr.1.1⟩ : PrimeSpectrum S) := by
          congr 1
          exact PrimeSpectrum.ext he.symm
        _ ≤ 1 := hrheight
    norm_num at hbad
  have hmapPrime : (r.map q).IsPrime := by
    apply Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
    simpa [q, I, Ideal.mk_ker] using hr.1.2
  have hker : RingHom.ker q = I := by
    ext z
    simp only [RingHom.mem_ker, q, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.Quotient.eq_zero_iff_mem
  have hstrict : r.map q < Q.map q := by
    apply lt_of_le_of_ne (Ideal.map_mono hrQstrict.le)
    intro he
    have hc := congrArg (Ideal.comap q) he
    simp only [Ideal.comap_map_of_surjective q Ideal.Quotient.mk_surjective,
      ← RingHom.ker_eq_comap_bot, hker,
      sup_eq_left.mpr hr.1.2, sup_eq_left.mpr hIQ] at hc
    exact (ne_of_lt hrQstrict) hc
  let A₀ : PrimeSpectrum T := ⟨r.map q, hmapPrime⟩
  let A₁ : PrimeSpectrum T := ⟨P, ‹P.IsPrime›⟩
  have h01 : A₀ < A₁ := by
    change r.map q < P
    simpa only [Ideal.map_comap_of_surjective q Ideal.Quotient.mk_surjective]
      using hstrict
  let v : LTSeries (PrimeSpectrum T) :=
    (RelSeries.singleton (· < ·) A₀).snoc A₁ h01
  have hheight : (1 : ℕ∞) ≤ Order.height A₁ := by
    simpa [v] using (Order.length_le_height_last (p := v))
  exact hheight.trans (by simpa [A₁] using height_le_atPrime_maximal_height P)

/-- At the generic point of the special fibre, the translated
integral surface has a one-dimensional regular-parameter
certificate: its maximal ideal is generated by the base
uniformizer. This does not cover other primes of the fibre. -/
theorem splitNode_specialFibreGeneric_regular_parameters
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let R := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
    let P := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
    letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
      (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
    let L := Localization.AtPrime P
    let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
      Ideal.Quotient.mk
        (Ideal.span {localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)})
    let t : L := (algebraMap R L) (q (MvPolynomial.C (2 : ℤ_[2])))
    IsNoetherianRing L ∧ ringKrullDim L = 1 ∧
      LocalRing.maximalIdeal L = Ideal.span {t} := by
  let S := MvPolynomial (Fin 2) ℤ_[2]
  let R := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let P : Ideal R := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P.IsPrime := (Ideal.Quotient.isDomain_iff_prime P).mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  let L := Localization.AtPrime P
  let q : S →+* R :=
    Ideal.Quotient.mk
      (Ideal.span {localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)})
  let f : R →+* L := algebraMap R L
  let t : L := f (q (MvPolynomial.C (2 : ℤ_[2])))
  haveI : IsNoetherianRing R :=
    isNoetherianRing_of_surjective S R q Ideal.Quotient.mk_surjective
  haveI : IsNoetherianRing L :=
    IsLocalization.isNoetherianRing P.primeCompl _ inferInstance
  have hP : P = Ideal.span {q (MvPolynomial.C (2 : ℤ_[2]))} :=
    localSurfaceSpecialFibreIdeal_eq_span_two W W.a₃ (W.a₃ ^ 2 + W.a₄)
  have hmax : LocalRing.maximalIdeal L = Ideal.span {t} := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal (I := P)]
    change Ideal.map f P = Ideal.span {t}
    calc
      Ideal.map f P =
          Ideal.map f (Ideal.span {q (MvPolynomial.C (2 : ℤ_[2]))}) :=
        congrArg (Ideal.map f) hP
      _ = Ideal.span {t} := by
        rw [Ideal.map_span]
        simp only [Set.image_singleton]
  have hmin : LocalRing.maximalIdeal L ∈
      (Ideal.span {t}).minimalPrimes := by
    rw [← hmax]
    exact ⟨⟨(LocalRing.maximalIdeal.isMaximal L).isPrime, le_rfl⟩,
      fun J hJ _ => hJ.2⟩
  let M : PrimeSpectrum L :=
    ⟨LocalRing.maximalIdeal L, (LocalRing.maximalIdeal.isMaximal L).isPrime⟩
  have hheight : Order.height M = 1 :=
    le_antisymm
      (minimal_prime_over_principal_height_le_one_general
        t (LocalRing.maximalIdeal L) hmin)
      (splitNode_specialFibreGeneric_height_ge_one W hnode hsplit)
  have hDim : ringKrullDim L = (↑(Order.height M) : WithBot ℕ∞) := by
    change Order.krullDim (PrimeSpectrum L) =
      (↑(Order.height M) : WithBot ℕ∞)
    rw [Order.krullDim_eq_iSup_height]
    apply le_antisymm
    · apply iSup_le
      intro Q
      exact WithBot.coe_le_coe.mpr
        (Order.height_mono (show Q ≤ M from
          LocalRing.le_maximalIdeal Q.isPrime.ne_top))
    · exact le_iSup_of_le M le_rfl
  exact ⟨inferInstance, by simpa only [hheight] using hDim, hmax⟩

/-- The generic special-fibre prime of the *actual* `Z = 1`
chart has a one-dimensional regular-parameter certificate. The
coordinate translation is used to transfer dimension; the
principal maximal ideal is proved in the original chart. -/
theorem splitNode_ZChart_specialFibreGeneric_regular_parameters
    (W : WeierstrassCurve ℤ_[2])
    (hnode : ReducedNodalPoint (W.map PadicInt.toZMod)
      (PadicInt.toZMod W.a₃)
      (PadicInt.toZMod (W.a₃ ^ 2 + W.a₄)))
    (hsplit : 3 * PadicInt.toZMod W.a₃ +
      (W.map PadicInt.toZMod).a₂ = 0) :
    let R := projectiveWeierstrassZChartRing W
    let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
      Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
    let P' := localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
    letI : P'.IsPrime := (Ideal.Quotient.isDomain_iff_prime P').mp
      (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
    let P := projectiveWeierstrassZChart_shiftPrime W W.a₃
      (W.a₃ ^ 2 + W.a₄) P'
    letI : P.IsPrime := Ideal.comap_isPrime
      (projectiveWeierstrassZChart_shiftEquiv W W.a₃
        (W.a₃ ^ 2 + W.a₄)).toRingEquiv.toRingHom P'
    let L := Localization.AtPrime P
    IsNoetherianRing L ∧ ringKrullDim L = 1 ∧
      LocalRing.maximalIdeal L =
        Ideal.span {(algebraMap R L) (q (MvPolynomial.C (2 : ℤ_[2])))} := by
  let R := projectiveWeierstrassZChartRing W
  let T := localSurfaceCoordinateRing W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let e : R ≃ₐ[ℤ_[2]] T :=
    projectiveWeierstrassZChart_shiftEquiv W W.a₃ (W.a₃ ^ 2 + W.a₄)
  let q : MvPolynomial (Fin 2) ℤ_[2] →+* R :=
    Ideal.Quotient.mk (Ideal.span {localSurfaceEquation W 0 0})
  let q' : MvPolynomial (Fin 2) ℤ_[2] →+* T :=
    Ideal.Quotient.mk (Ideal.span
      {localSurfaceEquation W W.a₃ (W.a₃ ^ 2 + W.a₄)})
  let t : R := q (MvPolynomial.C (2 : ℤ_[2]))
  let t' : T := q' (MvPolynomial.C (2 : ℤ_[2]))
  let P' : Ideal T :=
    localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)
  letI : P'.IsPrime := (Ideal.Quotient.isDomain_iff_prime P').mp
    (splitNode_affineSpecialFibre_isDomain W hnode hsplit)
  let P : Ideal R := projectiveWeierstrassZChart_shiftPrime W W.a₃
    (W.a₃ ^ 2 + W.a₄) P'
  letI : P.IsPrime := Ideal.comap_isPrime e.toRingEquiv.toRingHom P'
  let L := Localization.AtPrime P
  let f : R →+* L := algebraMap R L
  have hbase : e t = t' := by
    change e (algebraMap ℤ_[2] R 2) = algebraMap ℤ_[2] T 2
    exact e.commutes 2
  have hP : P = Ideal.span {t} := by
    change P'.comap (e.toRingEquiv : R →+* T) =
      (Ideal.span {t} : Ideal R)
    have ht : e.symm t' = t := by rw [← hbase, e.symm_apply_apply]
    calc
      P'.comap (e.toRingEquiv : R →+* T) =
          Ideal.map (e.toRingEquiv.symm : T →+* R) P' :=
        (Ideal.map_symm P' e.toRingEquiv).symm
      _ = Ideal.span {t} := by
        change Ideal.map (e.toRingEquiv.symm : T →+* R)
          (localSurfaceSpecialFibreIdeal W W.a₃ (W.a₃ ^ 2 + W.a₄)) =
            Ideal.span {t}
        rw [localSurfaceSpecialFibreIdeal_eq_span_two, Ideal.map_span]
        simp only [Set.image_singleton]
        change Ideal.span {e.symm t'} = Ideal.span {t}
        rw [ht]
  have hDim : ringKrullDim L = 1 := by
    exact (projectiveWeierstrassZChart_shiftLocalEquiv W W.a₃
      (W.a₃ ^ 2 + W.a₄) P').ringKrullDim.trans
        (splitNode_specialFibreGeneric_regular_parameters W hnode hsplit).2.1
  haveI : IsNoetherianRing L :=
    projectiveWeierstrassZChart_atPrime_isNoetherian W P
  have hmax : LocalRing.maximalIdeal L = Ideal.span {f t} := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal (I := P)]
    change Ideal.map f P = Ideal.span {f t}
    calc
      Ideal.map f P = Ideal.map f (Ideal.span {t}) :=
        congrArg (Ideal.map f) hP
      _ = Ideal.span {f t} := by
        rw [Ideal.map_span]
        simp only [Set.image_singleton]
  exact ⟨inferInstance, hDim, hmax⟩

end Beal.General