/-
  Galois/07h_OldNewOnV — old/new boundary on genuine-form generators

  This layer specifies what it means, without lattice closure, for a supplied
  Hecke-stable submodule to be generated by the finite genuine-form boundary.
  It then performs the valid logical transport from an explicit old/new
  hypothesis to a V-specific decomposition.

  No old/new decomposition is constructed here.  In particular, the finite
  coefficient model does not supply the localization, quotient, or geometric
  newform theorem needed to inhabit `OldNewDecompHyp`.
-/
import Beal.Galois.«07f_GenuineSubmodule»
import Beal.Galois.«07d_OldNew»

namespace Beal.Galois

/-- A constructively stated replacement for “the span of genuine forms”.

    `V` is Hecke-stable, contains every finite genuine-form sequence, and is
    contained in every other Hecke-stable submodule with that property.  This
    avoids `Submodule.span`, whose lattice implementation adds
    `Classical.choice` to the Lean 4.12 axiom audit. -/
def IsGenuineFormGeneratedAtLevel (M ℓ : ℕ)
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ)) : Prop :=
  IsModularFormAtLevel M ℓ V ∧
    (∀ f : CoefficientSequence ℓ,
      IsGenuineModularFormAtLevel M ℓ f → f ∈ V) ∧
      ∀ W : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
        IsModularFormAtLevel M ℓ W →
          (∀ f : CoefficientSequence ℓ,
            IsGenuineModularFormAtLevel M ℓ f → f ∈ W) →
              ∀ v : CoefficientSequence ℓ, v ∈ V → v ∈ W

/-- Conditional V-specific old/new decomposition.

    `OldNewDecompHyp` is an explicit proposition parameter, not a locally
    defined replacement theorem.  A future proof must inhabit it using the
    actual finite modular-form, localization, and quotient input. -/
theorem genuineFormGenerated_oldNew_of_hyp
    {M p ℓ : ℕ}
    (V : Submodule (ZMod ℓ) (CoefficientSequence ℓ))
    (hGenerated : IsGenuineFormGeneratedAtLevel M ℓ V)
    (OldNewDecompHyp : Prop)
    (hOldNew :
      OldNewDecompHyp →
        p.Prime ∧
          ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
            IsModularFormAtLevel M ℓ Old ∧
              IsModularFormAtLevel M ℓ New ∧
                IsInternalDirectSum V Old New)
    (hHyp : OldNewDecompHyp) :
    p.Prime ∧
      ∃ Old New : Submodule (ZMod ℓ) (CoefficientSequence ℓ),
        IsModularFormAtLevel M ℓ V ∧
          IsModularFormAtLevel M ℓ Old ∧
            IsModularFormAtLevel M ℓ New ∧
              IsInternalDirectSum V Old New := by
  rcases hOldNew hHyp with ⟨hp, Old, New, hOld, hNew, hSum⟩
  exact ⟨hp, Old, New, hGenerated.1, hOld, hNew, hSum⟩

-- MISSING: inhabit `OldNewDecompHyp` with the actual old/new decomposition
-- for the finite genuine-form-generated Hecke module.

#print axioms IsGenuineFormGeneratedAtLevel
#print axioms genuineFormGenerated_oldNew_of_hyp
-- Expected foundational dependencies: [propext, Quot.sound] only.

end Beal.Galois