import Beal.MathlibMissing.ChartInjective

/-!
`D₊(Yt)` for `Y² = X³ + 2` at `(0, 0)`.

`Yt` is the inverted degree-one class. The degree-zero coordinates are
`Y`, `X = Y · (Xt / Yt)`, and `U = 2t / Yt`. The cusp relation in this
chart is `Y² · (1 - Y · (Xt / Yt)³) = 0`.

That is not the v37 ideal. `modelXtChart ≃+* D₊(Xt)` uses
`U + X² + X·V²` with `V = Yt / Xt`, and `Xt` is not inverted here.
`modelYtTrueIdeal` is `(X - Y·S, Y²·(1 - Y·S³), Y·T, T²)` in
`𝔽₂[a,b][X,Y,S,T]`. Eliminating `X = Y·S` leaves
`𝔽₂[a,b][Y,S,T] / (Y²·(1 - Y·S³), Y·T, T²)`.
`chartOfModelTrueY` sends that quotient into `D₊(Yt)` and is surjective.
`D₊(Yt)` is generated by the degree-zero class `Y`, by `S = Xt/Yt`, and by
`T = 2t/Yt`, together with the coefficient ring `𝔽₂[a,b]`. The relation
`X = Y·S` is already in `modelYtTrueIdeal`.
The four-generator ideal does not present `D₊(Yt)`. From `2 = X³ − Y²`,
the chart satisfies `T + Y + Y²·S³ = 0`, and that polynomial lies outside
`modelYtTrueIdeal`. `chartOfModelTrueY` is not injective.
`modelYtTrueIdeal_fixed` is `(X − Y·S, T + Y + Y²·S³, Y²·(1 − Y·S³))`.
In characteristic 2, `Y·T` and `T²` follow from those three generators.
Eliminating `X = Y·S` and `T = Y + Y²·S³` gives
`𝔽₂[a,b][Y,S] / (Y²·(1 − Y·S³))`. The induced map onto `D₊(Yt)` is
surjective. Injectivity of that map is open, so there is no
`chart_Dplus_Yt_true_presentation`.

`D₊(2t)` is already the zero ring (`chart_Dplus_2t_subsingleton_valuationOne`).
A scheme gluing `Proj(Rees(I)/(2)) ≃ D₊(Xt) ∪ D₊(Yt)` is not claimed.
`BealEven` does not import this file.
-/

namespace Beal.MathlibMissing

open Beal.General

set_option synthInstance.maxHeartbeats 400000
set_option maxHeartbeats 8000000

private lemma yt_mem_centre_pow_zero
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) (r : surfaceRing W) :
    r ∈ numeralCentreIdeal W ap bq ^ 0 := by
  simp only [pow_zero, Ideal.one_eq_top, Submodule.mem_top]

private lemma yt_specialClass_mem_degree_one
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ)
    (r : surfaceRing W) (hr : r ∈ numeralCentreIdeal W ap bq) :
    (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq))
        (centreReesMonomial (numeralCentreIdeal W ap bq) 1
          ⟨r, by rw [pow_one]; exact hr⟩) ∈
      homogeneousQuotientComponent
        (centreReesComponent (numeralCentreIdeal W ap bq))
        (numeralReesSpecialIdeal W ap bq) 1 := by
  let I := numeralCentreIdeal W ap bq
  let J := numeralReesSpecialIdeal W ap bq
  have hy := centreReesComponent_monomial I 1 r (by rw [pow_one]; exact hr)
  change _ ∈ Submodule.map
    (Ideal.Quotient.mkₐ (surfaceRing W) J).toLinearMap (centreReesComponent I 1)
  exact Submodule.mem_map_of_mem hy

private lemma yt_specialClass_mem_degree_zero
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) (r : surfaceRing W) :
    (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq))
        (numeralReesConst W ap bq r) ∈
      homogeneousQuotientComponent
        (centreReesComponent (numeralCentreIdeal W ap bq))
        (numeralReesSpecialIdeal W ap bq) 0 := by
  let I := numeralCentreIdeal W ap bq
  let J := numeralReesSpecialIdeal W ap bq
  have hy := centreReesComponent_monomial I 0 r (yt_mem_centre_pow_zero W ap bq r)
  change _ ∈ Submodule.map
    (Ideal.Quotient.mkₐ (surfaceRing W) J).toLinearMap (centreReesComponent I 0)
  exact Submodule.mem_map_of_mem hy

private lemma yt_quotient_one_mem_degree_zero
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    (1 : reesAlgebra (numeralCentreIdeal W ap bq) ⧸
        numeralReesSpecialIdeal W ap bq) ∈
      homogeneousQuotientComponent
        (centreReesComponent (numeralCentreIdeal W ap bq))
        (numeralReesSpecialIdeal W ap bq) 0 := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hy : (1 : reesAlgebra I) ∈ centreReesComponent I 0 := by
    change ∃ r : ↥(I ^ 0), centreReesMonomial I 0 r = 1
    refine ⟨⟨1, by simp⟩, ?_⟩
    apply Subtype.ext
    simp [centreReesMonomial]
  have hmem : (Ideal.Quotient.mk J) (1 : reesAlgebra I) ∈
      homogeneousQuotientComponent (centreReesComponent I) J 0 :=
    Submodule.mem_map_of_mem hy
  rwa [map_one (Ideal.Quotient.mk J)] at hmem

/-- The degree-zero chart ring `(Rees(I)/(2))_((Y - bq) t)`. -/
noncomputable def chart_Dplus_Yt_ring
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) : Type :=
  let I := numeralCentreIdeal W ap bq
  let J := numeralReesSpecialIdeal W ap bq
  let _ : Algebra (surfaceRing W) (reesAlgebra I) := inferInstance
  let _ : Algebra (surfaceRing W) (reesAlgebra I ⧸ J) := inferInstance
  HomogeneousLocalization.Away
    (homogeneousQuotientComponent (centreReesComponent I) J)
    (Ideal.Quotient.mk J (numeralReesYT W ap bq))

noncomputable instance chartYtCommRing
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    CommRing (chart_Dplus_Yt_ring W ap bq) := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  unfold chart_Dplus_Yt_ring
  infer_instance

/-- `2t / Yt` on `D₊(Yt)`. -/
noncomputable def chartYt_two_over_Y (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chart_Dplus_Yt_ring W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ :=
    homogeneousQuotientGrading (centreReesComponent I) J
      (numeralReesSpecialIdeal_isHomogeneous W ap bq)
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  let num := Ideal.Quotient.mk J (numeralReesTwo W ap bq)
  exact HomogeneousLocalization.mk
    ⟨1,
      ⟨num, by
        simpa [num, numeralReesTwo] using
          yt_specialClass_mem_degree_one W ap bq (2 : surfaceRing W)
            (two_mem_numeralCentreIdeal W ap bq)⟩,
      ⟨f, by
        simpa [f, numeralReesYT] using
          yt_specialClass_mem_degree_one W ap bq
            (Ideal.Quotient.mk (Ideal.span {surfacePolynomial W})
              (MvPolynomial.X (1 : Fin 2) -
                MvPolynomial.C (MvPolynomial.C (bq : ℤ_[2]))))
            (numeral_Y_mem_centre W ap bq)⟩,
      ⟨1, pow_one _⟩⟩

/-- `Xt / Yt` on `D₊(Yt)`. -/
noncomputable def chartYt_X_over_Y (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chart_Dplus_Yt_ring W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ :=
    homogeneousQuotientGrading (centreReesComponent I) J
      (numeralReesSpecialIdeal_isHomogeneous W ap bq)
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  let num := Ideal.Quotient.mk J (numeralReesXT W ap bq)
  exact HomogeneousLocalization.mk
    ⟨1,
      ⟨num, by
        simpa [num, numeralReesXT] using
          yt_specialClass_mem_degree_one W ap bq
            (Ideal.Quotient.mk (Ideal.span {surfacePolynomial W})
              (MvPolynomial.X (0 : Fin 2) -
                MvPolynomial.C (MvPolynomial.C (ap : ℤ_[2]))))
            (numeral_X_mem_centre W ap bq)⟩,
      ⟨f, by
        simpa [f, numeralReesYT] using
          yt_specialClass_mem_degree_one W ap bq
            (Ideal.Quotient.mk (Ideal.span {surfacePolynomial W})
              (MvPolynomial.X (1 : Fin 2) -
                MvPolynomial.C (MvPolynomial.C (bq : ℤ_[2]))))
            (numeral_Y_mem_centre W ap bq)⟩,
      ⟨1, pow_one _⟩⟩

/-- Degree-zero class of `Y - bq` on `D₊(Yt)`. -/
noncomputable def chartYt_Y (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chart_Dplus_Yt_ring W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ :=
    homogeneousQuotientGrading (centreReesComponent I) J
      (numeralReesSpecialIdeal_isHomogeneous W ap bq)
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  let num := Ideal.Quotient.mk J (numeralReesConst W ap bq (surfaceNumeralY W bq))
  exact HomogeneousLocalization.mk
    ⟨0,
      ⟨num, by
        simpa [num] using
          yt_specialClass_mem_degree_zero W ap bq (surfaceNumeralY W bq)⟩,
      ⟨(1 : reesAlgebra I ⧸ J), yt_quotient_one_mem_degree_zero W ap bq⟩,
      ⟨0, pow_zero f⟩⟩

/-- Degree-zero class of `X - ap` on `D₊(Yt)`. -/
noncomputable def chartYt_X (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chart_Dplus_Yt_ring W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ :=
    homogeneousQuotientGrading (centreReesComponent I) J
      (numeralReesSpecialIdeal_isHomogeneous W ap bq)
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  let num := Ideal.Quotient.mk J (numeralReesConst W ap bq (surfaceNumeralX W ap))
  exact HomogeneousLocalization.mk
    ⟨0,
      ⟨num, by
        simpa [num] using
          yt_specialClass_mem_degree_zero W ap bq (surfaceNumeralX W ap)⟩,
      ⟨(1 : reesAlgebra I ⧸ J), yt_quotient_one_mem_degree_zero W ap bq⟩,
      ⟨0, pow_zero f⟩⟩

private lemma yt_mul_const_X_eq_const_Y_mul_xt
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    numeralReesYT W ap bq * numeralReesConst W ap bq (surfaceNumeralX W ap) =
      numeralReesConst W ap bq (surfaceNumeralY W bq) * numeralReesXT W ap bq := by
  apply Subtype.ext
  unfold numeralReesXT numeralReesYT numeralReesConst centreReesMonomial
    surfaceNumeralX surfaceNumeralY
  rw [Subalgebra.coe_mul, Subalgebra.coe_mul]
  dsimp
  rw [Polynomial.monomial_mul_C, Polynomial.C_mul_monomial]

private lemma const_Y_mul_two_eq_scalar_two_mul_yt
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    numeralReesConst W ap bq (surfaceNumeralY W bq) * numeralReesTwo W ap bq =
      algebraMap (surfaceRing W) (reesAlgebra (numeralCentreIdeal W ap bq))
          (2 : surfaceRing W) *
        numeralReesYT W ap bq := by
  apply Subtype.ext
  unfold numeralReesConst numeralReesTwo numeralReesYT centreReesMonomial surfaceNumeralY
  rw [Subalgebra.coe_mul, Subalgebra.coe_mul, Subalgebra.coe_algebraMap]
  dsimp
  rw [Polynomial.C_mul_monomial]
  have hcoef := mul_comm
    ((Ideal.Quotient.mk (Ideal.span {surfacePolynomial W}))
      (MvPolynomial.X (1 : Fin 2) - MvPolynomial.C (MvPolynomial.C (bq : ℤ_[2]))))
    (2 : surfaceRing W)
  rw [hcoef, ← Polynomial.C_mul_monomial]

/-- `X = Y · (Xt / Yt)` on `D₊(Yt)`. -/
theorem chartYt_X_eq_Y_mul_X_over_Y
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chartYt_X W ap bq = chartYt_Y W ap bq * chartYt_X_over_Y W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  erw [HomogeneousLocalization.val_mul]
  simp only [chartYt_X, chartYt_Y, chartYt_X_over_Y, HomogeneousLocalization.val_mk]
  rw [Localization.mk_mul, Localization.mk_eq_mk_iff]
  refine Localization.r_iff_exists.mpr ⟨1, ?_⟩
  have hcomm := congrArg (Ideal.Quotient.mk J)
    (yt_mul_const_X_eq_const_Y_mul_xt W ap bq)
  rw [map_mul, map_mul] at hcomm
  dsimp
  rw [one_mul (((1 : reesAlgebra I ⧸ J) *
      (Ideal.Quotient.mk J) (numeralReesYT W ap bq)) *
    (Ideal.Quotient.mk J) (numeralReesConst W ap bq (surfaceNumeralX W ap)))]
  rw [one_mul ((1 : reesAlgebra I ⧸ J) *
    ((Ideal.Quotient.mk J) (numeralReesConst W ap bq (surfaceNumeralY W bq)) *
      (Ideal.Quotient.mk J) (numeralReesXT W ap bq)))]
  rw [one_mul ((Ideal.Quotient.mk J) (numeralReesYT W ap bq))]
  rw [one_mul ((Ideal.Quotient.mk J) (numeralReesConst W ap bq (surfaceNumeralY W bq)) *
    (Ideal.Quotient.mk J) (numeralReesXT W ap bq))]
  exact hcomm

/-- `Y · (2t / Yt) = 0` on `D₊(Yt)`, because the numerator is the scalar `2`. -/
theorem chartYt_Y_mul_two_over_Y_eq_zero
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chartYt_Y W ap bq * chartYt_two_over_Y W ap bq = 0 := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  erw [HomogeneousLocalization.val_mul, HomogeneousLocalization.val_zero]
  simp only [chartYt_Y, chartYt_two_over_Y, HomogeneousLocalization.val_mk]
  rw [Localization.mk_mul]
  have hnum :
      Ideal.Quotient.mk J (numeralReesConst W ap bq (surfaceNumeralY W bq)) *
        Ideal.Quotient.mk J (numeralReesTwo W ap bq) = 0 := by
    rw [← map_mul, const_Y_mul_two_eq_scalar_two_mul_yt, map_mul]
    have h2 : Ideal.Quotient.mk J
        (algebraMap (surfaceRing W) (reesAlgebra I) (2 : surfaceRing W)) = 0 := by
      rw [Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.mem_span_singleton_self _
    rw [h2]
    exact zero_mul ((Ideal.Quotient.mk J) (numeralReesYT W ap bq))
  rw [hnum]
  rw [← Localization.mk_zero (1 : Submonoid.powers f)]
  rw [Localization.mk_eq_mk_iff]
  refine Localization.r_iff_exists.mpr ⟨1, ?_⟩
  dsimp
  rw [mul_zero ((1 : reesAlgebra I ⧸ J) *
    (Ideal.Quotient.mk J) (numeralReesYT W ap bq))]
  rw [mul_zero (1 : reesAlgebra I ⧸ J)]
  rw [mul_zero (1 : reesAlgebra I ⧸ J)]

/-- On `Y² = X³ + 2` at `(0, 0)`, `Y² = X³` in `D₊(Yt)`. -/
theorem chartYt_Y_sq_eq_X_cu :
    chartYt_Y valuationOneCurve 0 0 ^ 2 = chartYt_X valuationOneCurve 0 0 ^ 3 := by
  let I := numeralCentreIdeal valuationOneCurve 0 0
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal valuationOneCurve 0 0
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous valuationOneCurve 0 0
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT valuationOneCurve 0 0)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  erw [HomogeneousLocalization.val_pow, HomogeneousLocalization.val_pow]
  simp only [chartYt_Y, chartYt_X, HomogeneousLocalization.val_mk]
  rw [Localization.mk_pow, Localization.mk_pow, Localization.mk_eq_mk_iff]
  refine Localization.r_iff_exists.mpr ⟨1, ?_⟩
  dsimp
  change (1 : reesAlgebra I ⧸ J) *
      ((1 : reesAlgebra I ⧸ J) ^ 3 *
        (Ideal.Quotient.mk J
          (numeralReesConst valuationOneCurve 0 0
            (surfaceNumeralY valuationOneCurve 0))) ^ 2) =
    (1 : reesAlgebra I ⧸ J) *
      ((1 : reesAlgebra I ⧸ J) ^ 2 *
        (Ideal.Quotient.mk J
          (numeralReesConst valuationOneCurve 0 0
            (surfaceNumeralX valuationOneCurve 0))) ^ 3)
  have h3 : (1 : reesAlgebra I ⧸ J) ^ 3 = 1 := one_pow _
  have h2 : (1 : reesAlgebra I ⧸ J) ^ 2 = 1 := one_pow _
  rw [h3, h2]
  set y := (Ideal.Quotient.mk J
      (numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0))) ^ 2
  set x := (Ideal.Quotient.mk J
      (numeralReesConst valuationOneCurve 0 0 (surfaceNumeralX valuationOneCurve 0))) ^ 3
  rw [one_mul (1 * y), one_mul y, one_mul (1 * x), one_mul x]
  exact valuationOne_special_const_Ysq_eq_Xcu

/-- The `Yt` cusp relation: `Y² · (1 - Y · (Xt / Yt)³) = 0`.
Substituting `X = Y · (Xt / Yt)` into `Y² = X³` gives this, not
`X² · (X + V²) = 0`. -/
theorem chartYt_cusp_relation :
    chartYt_Y valuationOneCurve 0 0 ^ 2 *
      (1 - chartYt_Y valuationOneCurve 0 0 *
        chartYt_X_over_Y valuationOneCurve 0 0 ^ 3) = 0 := by
  set y : chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
    chartYt_Y valuationOneCurve 0 0
  set s : chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
    chartYt_X_over_Y valuationOneCurve 0 0
  set x : chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
    chartYt_X valuationOneCurve 0 0
  have hx : x = y * s := chartYt_X_eq_Y_mul_X_over_Y _ _ _
  have hy : y ^ 2 = x ^ 3 := chartYt_Y_sq_eq_X_cu
  have hfac : y ^ 2 * (1 - y * s ^ 3) = y ^ 2 - (y * s) ^ 3 := by ring
  rw [hfac, ← hx, ← hy, sub_self]

/-- `(2t / Yt)² = 0` on this node, because `(2t)² = 0` in `Rees/(2)`. -/
theorem chartYt_two_over_Y_sq_zero :
    chartYt_two_over_Y valuationOneCurve 0 0 ^ 2 = 0 := by
  let I := numeralCentreIdeal valuationOneCurve 0 0
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal valuationOneCurve 0 0
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous valuationOneCurve 0 0
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT valuationOneCurve 0 0)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  erw [HomogeneousLocalization.val_pow, HomogeneousLocalization.val_zero]
  simp only [chartYt_two_over_Y, HomogeneousLocalization.val_mk]
  rw [Localization.mk_pow]
  have hsq :
      (Ideal.Quotient.mk J (numeralReesTwo valuationOneCurve 0 0)) ^ 2 = 0 :=
    valuationOne_specialTwo_sq_zero
  rw [hsq, Localization.mk]
  simp

private lemma yt_numeralReesConst_eq_algebraMap
    (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) (r : surfaceRing W) :
    numeralReesConst W ap bq r =
      algebraMap (surfaceRing W) (reesAlgebra (numeralCentreIdeal W ap bq)) r := by
  apply Subtype.ext
  unfold numeralReesConst centreReesMonomial
  rw [Subalgebra.coe_algebraMap]
  dsimp

/-- Degree-zero class of a surface element on `D₊(Yt)`. -/
noncomputable def chartYtConst (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ)
    (r : surfaceRing W) : chart_Dplus_Yt_ring W ap bq := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ :=
    homogeneousQuotientGrading (centreReesComponent I) J
      (numeralReesSpecialIdeal_isHomogeneous W ap bq)
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  let num := Ideal.Quotient.mk J (numeralReesConst W ap bq r)
  exact HomogeneousLocalization.mk
    ⟨0,
      ⟨num, by
        simpa [num] using yt_specialClass_mem_degree_zero W ap bq r⟩,
      ⟨(1 : reesAlgebra I ⧸ J), yt_quotient_one_mem_degree_zero W ap bq⟩,
      ⟨0, pow_zero f⟩⟩

private lemma chartYtConst_val (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ)
    (r : surfaceRing W) :
    (chartYtConst W ap bq r).val =
      Localization.mk
        (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq)
          (numeralReesConst W ap bq r))
        (1 : Submonoid.powers
          (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq)
            (numeralReesYT W ap bq))) := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  simp [chartYtConst, HomogeneousLocalization.val_mk]
  rfl

private lemma chartYtConst_mul (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ)
    (r s : surfaceRing W) :
    chartYtConst W ap bq (r * s) = chartYtConst W ap bq r * chartYtConst W ap bq s := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  rw [HomogeneousLocalization.val_mul, chartYtConst_val, chartYtConst_val, chartYtConst_val,
    Localization.mk_mul]
  have hden : (1 : Submonoid.powers f) * 1 = 1 := mul_one _
  rw [hden]
  congr 1
  rw [← map_mul (Ideal.Quotient.mk J), yt_numeralReesConst_eq_algebraMap,
    yt_numeralReesConst_eq_algebraMap, yt_numeralReesConst_eq_algebraMap, map_mul]

private lemma chartYtConst_add (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ)
    (r s : surfaceRing W) :
    chartYtConst W ap bq (r + s) = chartYtConst W ap bq r + chartYtConst W ap bq s := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  rw [HomogeneousLocalization.val_add, chartYtConst_val, chartYtConst_val, chartYtConst_val]
  rw [Localization.add_mk_self
      (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq) (numeralReesConst W ap bq r))
      (1 : Submonoid.powers f)
      (Ideal.Quotient.mk (numeralReesSpecialIdeal W ap bq) (numeralReesConst W ap bq s))]
  congr 1
  rw [← map_add (Ideal.Quotient.mk J), yt_numeralReesConst_eq_algebraMap,
    yt_numeralReesConst_eq_algebraMap, yt_numeralReesConst_eq_algebraMap, map_add]

private lemma chartYtConst_one (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chartYtConst W ap bq (1 : surfaceRing W) = 1 := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  rw [chartYtConst_val, HomogeneousLocalization.val_one, yt_numeralReesConst_eq_algebraMap,
    map_one, map_one, Localization.mk_one]

private lemma chartYtConst_zero (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chartYtConst W ap bq (0 : surfaceRing W) = 0 := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  rw [chartYtConst_val, HomogeneousLocalization.val_zero, yt_numeralReesConst_eq_algebraMap,
    map_zero, map_zero]
  exact Localization.mk_zero (1 : Submonoid.powers f)

noncomputable def chartYtConstHom (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    surfaceRing W →+* chart_Dplus_Yt_ring W ap bq where
  toFun := chartYtConst W ap bq
  map_one' := chartYtConst_one W ap bq
  map_mul' := chartYtConst_mul W ap bq
  map_zero' := chartYtConst_zero W ap bq
  map_add' := chartYtConst_add W ap bq

noncomputable def chartYtScalar (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    S →+* chart_Dplus_Yt_ring W ap bq :=
  (chartYtConstHom W ap bq).comp (algebraMap S (surfaceRing W))

theorem chartYtScalar_C_two (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    chartYtScalar W ap bq (MvPolynomial.C (2 : ℤ_[2])) = 0 := by
  let I := numeralCentreIdeal W ap bq
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal W ap bq
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous W ap bq
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let f := Ideal.Quotient.mk J (numeralReesYT W ap bq)
  rw [chartYtScalar, RingHom.comp_apply]
  have htwo : algebraMap S (surfaceRing W) (MvPolynomial.C (2 : ℤ_[2])) =
      (2 : surfaceRing W) := by
    rw [two_eq_quotient_mk]
    rfl
  rw [htwo]
  dsimp [chartYtConstHom]
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  rw [chartYtConst_val, HomogeneousLocalization.val_zero, yt_numeralReesConst_eq_algebraMap]
  have hJ0 : Ideal.Quotient.mk J
      (algebraMap (surfaceRing W) (reesAlgebra I) (2 : surfaceRing W)) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)
  rw [hJ0]
  exact Localization.mk_zero (1 : Submonoid.powers f)

noncomputable def chartYtScalarModTwo (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    S ⧸ Ideal.span {MvPolynomial.C (2 : ℤ_[2])} →+* chart_Dplus_Yt_ring W ap bq :=
  Ideal.Quotient.lift (Ideal.span {MvPolynomial.C (2 : ℤ_[2])}) (chartYtScalar W ap bq)
    (by
      intro a ha
      obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp ha
      rw [map_mul, chartYtScalar_C_two, mul_zero])

/-- `𝔽₂[a,b] → D₊(Yt)`. -/
noncomputable def chartYtFromF2Polynomial (W : WeierstrassCurve ℤ_[2]) (ap bq : ℕ) :
    MvPolynomial (Fin 2) (ZMod 2) →+* chart_Dplus_Yt_ring W ap bq :=
  (chartYtScalarModTwo W ap bq).comp coeffModTwoEquiv.symm.toRingHom

/-- `(X - Y·S, Y²·(1 - Y·S³), Y·T, T²)` in `𝔽₂[a,b][X,Y,S,T]`.
`0` is `X`, `1` is `Y`, `2` is `S = Xt/Yt`, `3` is `T = 2t/Yt`. -/
noncomputable def modelYtTrueIdeal :
    Ideal (MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2))) :=
  Ideal.span {
    MvPolynomial.X 0 - MvPolynomial.X 1 * MvPolynomial.X 2,
    (MvPolynomial.X 1) ^ 2 * (1 - MvPolynomial.X 1 * (MvPolynomial.X 2) ^ 3),
    MvPolynomial.X 1 * MvPolynomial.X 3,
    (MvPolynomial.X 3) ^ 2 }

/-- `𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal`. -/
abbrev modelYtChart : Type :=
  MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) ⧸ modelYtTrueIdeal

/-- Send `X, Y, S, T` to `X`, `Y`, `Xt/Yt`, `2t/Yt` in `D₊(Yt)`. -/
noncomputable def chartYtModelEval :
    MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) →+*
      chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
  MvPolynomial.eval₂Hom (chartYtFromF2Polynomial valuationOneCurve 0 0)
    (fun i : Fin 4 =>
      if i = 0 then chartYt_X valuationOneCurve 0 0
      else if i = 1 then chartYt_Y valuationOneCurve 0 0
      else if i = 2 then chartYt_X_over_Y valuationOneCurve 0 0
      else chartYt_two_over_Y valuationOneCurve 0 0)

private lemma chartYtModelEval_X (i : Fin 4) :
    chartYtModelEval (MvPolynomial.X i) =
      if i = 0 then chartYt_X valuationOneCurve 0 0
      else if i = 1 then chartYt_Y valuationOneCurve 0 0
      else if i = 2 then chartYt_X_over_Y valuationOneCurve 0 0
      else chartYt_two_over_Y valuationOneCurve 0 0 := by
  simp [chartYtModelEval, MvPolynomial.eval₂Hom_X']

theorem modelYtTrueIdeal_le_ker_chartYtModelEval :
    modelYtTrueIdeal ≤ RingHom.ker chartYtModelEval := by
  rw [modelYtTrueIdeal, Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl | rfl
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_sub, map_mul, chartYtModelEval_X,
      chartYtModelEval_X, chartYtModelEval_X,
      if_pos (rfl : (0 : Fin 4) = 0),
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2),
      chartYt_X_eq_Y_mul_X_over_Y, sub_self]
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_mul, map_pow, map_sub, map_one, map_mul, map_pow,
      chartYtModelEval_X, chartYtModelEval_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    exact chartYt_cusp_relation
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_mul, chartYtModelEval_X, chartYtModelEval_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (3 : Fin 4) ≠ 0),
      if_neg (by decide : (3 : Fin 4) ≠ 1),
      if_neg (by decide : (3 : Fin 4) ≠ 2),
      chartYt_Y_mul_two_over_Y_eq_zero]
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_pow, chartYtModelEval_X,
      if_neg (by decide : (3 : Fin 4) ≠ 0),
      if_neg (by decide : (3 : Fin 4) ≠ 1),
      if_neg (by decide : (3 : Fin 4) ≠ 2),
      chartYt_two_over_Y_sq_zero]

/-- `𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal → D₊(Yt)`. -/
noncomputable def chartOfModelTrueY :
    modelYtChart →+* chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
  Ideal.Quotient.lift modelYtTrueIdeal chartYtModelEval modelYtTrueIdeal_le_ker_chartYtModelEval

/-!
Eliminating `X` by `X = Y·S`. The normal ring still has `T`, with
`Y·T = 0` and `T² = 0`. It is not `𝔽₂[a,b][Y,S]` alone, and it is not
the `Xt` normal form `A(V) + X·B(V) + X²·C(V)`.
-/

abbrev chartYtNormalPoly : Type :=
  MvPolynomial (Fin 3) (MvPolynomial (Fin 2) (ZMod 2))

noncomputable def chartYtNormalRelY :
    chartYtNormalPoly :=
  (MvPolynomial.X 0) ^ 2 * (1 - MvPolynomial.X 0 * (MvPolynomial.X 1) ^ 3)

noncomputable def chartYtNormalRelT :
    chartYtNormalPoly :=
  MvPolynomial.X 0 * MvPolynomial.X 2

noncomputable def chartYtNormalRelTsq :
    chartYtNormalPoly :=
  (MvPolynomial.X 2) ^ 2

noncomputable def chartYtNormalIdeal : Ideal chartYtNormalPoly :=
  Ideal.span {chartYtNormalRelY, chartYtNormalRelT, chartYtNormalRelTsq}

abbrev chartYtNormalRing : Type := chartYtNormalPoly ⧸ chartYtNormalIdeal

/-- Send `X, Y, S, T` to `Y·S, Y, S, T`. -/
noncomputable def chartYtToNormalEval :
    MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) →+* chartYtNormalRing :=
  MvPolynomial.eval₂Hom
    ((Ideal.Quotient.mk chartYtNormalIdeal).comp MvPolynomial.C)
    (fun i : Fin 4 =>
      if i = 0 then
        Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 0 * MvPolynomial.X 1)
      else if i = 1 then Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 0)
      else if i = 2 then Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 1)
      else Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 2))

private lemma chartYtToNormalEval_X (i : Fin 4) :
    chartYtToNormalEval (MvPolynomial.X i) =
      if i = 0 then
        Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 0 * MvPolynomial.X 1)
      else if i = 1 then Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 0)
      else if i = 2 then Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 1)
      else Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X 2) := by
  simp [chartYtToNormalEval, MvPolynomial.eval₂Hom_X']

theorem chartYtToNormalEval_kills :
    modelYtTrueIdeal ≤ RingHom.ker chartYtToNormalEval := by
  rw [modelYtTrueIdeal, Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl | rfl
  · rw [CharTwo.sub_eq_add, SetLike.mem_coe, RingHom.mem_ker, map_add, map_mul,
      chartYtToNormalEval_X, chartYtToNormalEval_X, chartYtToNormalEval_X,
      if_pos (rfl : (0 : Fin 4) = 0),
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    rw [map_mul (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_add (Ideal.Quotient.mk chartYtNormalIdeal),
      CharTwo.add_self_eq_zero, map_zero]
  · rw [CharTwo.sub_eq_add, SetLike.mem_coe, RingHom.mem_ker, map_mul, map_pow, map_add,
      map_one, map_mul, map_pow, chartYtToNormalEval_X, chartYtToNormalEval_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    rw [← map_pow (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_pow (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_one (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_add (Ideal.Quotient.mk chartYtNormalIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtNormalIdeal),
      ← CharTwo.sub_eq_add, Ideal.Quotient.eq_zero_iff_mem]
    rw [chartYtNormalIdeal]
    exact Ideal.subset_span (Set.mem_insert _ _)
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_mul, chartYtToNormalEval_X,
      chartYtToNormalEval_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (3 : Fin 4) ≠ 0),
      if_neg (by decide : (3 : Fin 4) ≠ 1),
      if_neg (by decide : (3 : Fin 4) ≠ 2)]
    rw [← map_mul (Ideal.Quotient.mk chartYtNormalIdeal), Ideal.Quotient.eq_zero_iff_mem]
    rw [chartYtNormalIdeal]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_pow, chartYtToNormalEval_X,
      if_neg (by decide : (3 : Fin 4) ≠ 0),
      if_neg (by decide : (3 : Fin 4) ≠ 1),
      if_neg (by decide : (3 : Fin 4) ≠ 2)]
    rw [← map_pow (Ideal.Quotient.mk chartYtNormalIdeal), Ideal.Quotient.eq_zero_iff_mem]
    rw [chartYtNormalIdeal]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _
      (Set.mem_singleton _)))

noncomputable def chartYtToNormal :
    modelYtChart →+* chartYtNormalRing :=
  Ideal.Quotient.lift modelYtTrueIdeal chartYtToNormalEval chartYtToNormalEval_kills

/-- Include `Y, S, T` as the last three variables. -/
noncomputable def normalYtToModel :
    chartYtNormalPoly →+* MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) :=
  MvPolynomial.eval₂Hom MvPolynomial.C
    (fun i : Fin 3 =>
      if i = 0 then MvPolynomial.X 1
      else if i = 1 then MvPolynomial.X 2
      else MvPolynomial.X 3)

private lemma normalYtToModel_relY :
    normalYtToModel chartYtNormalRelY =
      (MvPolynomial.X (1 : Fin 4)) ^ 2 *
        (1 - MvPolynomial.X 1 * (MvPolynomial.X 2) ^ 3) := by
  rw [chartYtNormalRelY, CharTwo.sub_eq_add, normalYtToModel, map_mul, map_pow, map_add,
    map_one, map_mul, map_pow, MvPolynomial.eval₂Hom_X', MvPolynomial.eval₂Hom_X',
    if_pos (rfl : (0 : Fin 3) = 0),
    if_neg (by decide : (1 : Fin 3) ≠ 0),
    if_pos (rfl : (1 : Fin 3) = 1),
    ← CharTwo.sub_eq_add]

private lemma normalYtToModel_relT :
    normalYtToModel chartYtNormalRelT =
      MvPolynomial.X (1 : Fin 4) * MvPolynomial.X 3 := by
  rw [chartYtNormalRelT, normalYtToModel, map_mul, MvPolynomial.eval₂Hom_X',
    MvPolynomial.eval₂Hom_X',
    if_pos (rfl : (0 : Fin 3) = 0),
    if_neg (by decide : (2 : Fin 3) ≠ 0),
    if_neg (by decide : (2 : Fin 3) ≠ 1)]

private lemma normalYtToModel_relTsq :
    normalYtToModel chartYtNormalRelTsq = (MvPolynomial.X (3 : Fin 4)) ^ 2 := by
  rw [chartYtNormalRelTsq, normalYtToModel, map_pow, MvPolynomial.eval₂Hom_X',
    if_neg (by decide : (2 : Fin 3) ≠ 0),
    if_neg (by decide : (2 : Fin 3) ≠ 1)]

theorem normalYtToModel_kills :
    chartYtNormalIdeal ≤
      RingHom.ker ((Ideal.Quotient.mk modelYtTrueIdeal).comp normalYtToModel) := by
  rw [chartYtNormalIdeal, Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl
  · rw [SetLike.mem_coe, RingHom.mem_ker, RingHom.comp_apply, normalYtToModel_relY,
      Ideal.Quotient.eq_zero_iff_mem, modelYtTrueIdeal]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  · rw [SetLike.mem_coe, RingHom.mem_ker, RingHom.comp_apply, normalYtToModel_relT,
      Ideal.Quotient.eq_zero_iff_mem, modelYtTrueIdeal]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _
      (Set.mem_insert _ _)))
  · rw [SetLike.mem_coe, RingHom.mem_ker, RingHom.comp_apply, normalYtToModel_relTsq,
      Ideal.Quotient.eq_zero_iff_mem, modelYtTrueIdeal]
    exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _
      (Set.mem_insert_of_mem _ (Set.mem_singleton _))))

noncomputable def normalYtToChart :
    chartYtNormalRing →+* modelYtChart :=
  Ideal.Quotient.lift chartYtNormalIdeal
    ((Ideal.Quotient.mk modelYtTrueIdeal).comp normalYtToModel) normalYtToModel_kills

private lemma chartYt_fin4 (i j : Fin 4) (h : i.val = j.val) :
    Ideal.Quotient.mk modelYtTrueIdeal (MvPolynomial.X i) =
      Ideal.Quotient.mk modelYtTrueIdeal (MvPolynomial.X j) :=
  congrArg (fun k : Fin 4 => Ideal.Quotient.mk modelYtTrueIdeal (MvPolynomial.X k))
    (Fin.ext h)

private lemma chartYt_fin3 (i j : Fin 3) (h : i.val = j.val) :
    Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X i) =
      Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X j) :=
  congrArg (fun k : Fin 3 => Ideal.Quotient.mk chartYtNormalIdeal (MvPolynomial.X k))
    (Fin.ext h)

private lemma chartYtToNormal_comp_normalYtToChart :
    chartYtToNormal.comp normalYtToChart = RingHom.id chartYtNormalRing := by
  apply Ideal.Quotient.ringHom_ext
  apply MvPolynomial.ringHom_ext
  · intro r
    simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, chartYtToNormalEval,
      normalYtToChart, normalYtToModel, Ideal.Quotient.lift_mk, MvPolynomial.eval₂Hom_C]
  · intro i
    fin_cases i
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, normalYtToChart,
        Ideal.Quotient.lift_mk, chartYtToNormalEval, normalYtToModel, MvPolynomial.eval₂Hom_X']
      rw [if_pos (by decide), MvPolynomial.eval₂Hom_X',
        if_neg (by decide : (1 : Fin 4) ≠ 0), if_pos (by decide : (1 : Fin 4) = 1)]
      exact chartYt_fin3 (0 : Fin 3) ⟨0, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, normalYtToChart,
        Ideal.Quotient.lift_mk, chartYtToNormalEval, normalYtToModel, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_pos (by decide),
        MvPolynomial.eval₂Hom_X',
        if_neg (by decide : (2 : Fin 4) ≠ 0), if_neg (by decide : (2 : Fin 4) ≠ 1),
        if_pos (by decide : (2 : Fin 4) = 2)]
      exact chartYt_fin3 (1 : Fin 3) ⟨1, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, normalYtToChart,
        Ideal.Quotient.lift_mk, chartYtToNormalEval, normalYtToModel, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_neg (by decide),
        MvPolynomial.eval₂Hom_X',
        if_neg (by decide : (3 : Fin 4) ≠ 0), if_neg (by decide : (3 : Fin 4) ≠ 1),
        if_neg (by decide : (3 : Fin 4) ≠ 2)]
      exact chartYt_fin3 (2 : Fin 3) ⟨2, by decide⟩ rfl

private lemma normalYtToChart_comp_chartYtToNormal :
    normalYtToChart.comp chartYtToNormal = RingHom.id _ := by
  apply Ideal.Quotient.ringHom_ext
  apply MvPolynomial.ringHom_ext
  · intro r
    simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, chartYtToNormalEval,
      normalYtToChart, normalYtToModel, Ideal.Quotient.lift_mk, MvPolynomial.eval₂Hom_C]
  · intro i
    fin_cases i
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, Ideal.Quotient.lift_mk,
        chartYtToNormalEval, MvPolynomial.eval₂Hom_X']
      rw [if_pos (by decide)]
      simp only [normalYtToChart, Ideal.Quotient.lift_mk, RingHom.comp_apply, normalYtToModel,
        map_mul, MvPolynomial.eval₂Hom_X']
      rw [if_true, if_neg (by decide : (1 : Fin 3) ≠ 0), if_true]
      rw [← map_mul (Ideal.Quotient.mk modelYtTrueIdeal), Ideal.Quotient.eq]
      have hmem (j : Fin 4) (hj : j = 0) :
          MvPolynomial.X 1 * MvPolynomial.X 2 - MvPolynomial.X j ∈ modelYtTrueIdeal := by
        subst hj
        rw [CharTwo.sub_eq_add, add_comm, ← CharTwo.sub_eq_add, modelYtTrueIdeal]
        exact Ideal.subset_span (Set.mem_insert _ _)
      apply hmem
      exact Fin.ext rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, Ideal.Quotient.lift_mk,
        chartYtToNormalEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_pos (by decide)]
      simp only [normalYtToChart, Ideal.Quotient.lift_mk, RingHom.comp_apply, normalYtToModel,
        MvPolynomial.eval₂Hom_X']
      rw [if_true]
      exact chartYt_fin4 1 ⟨1, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, Ideal.Quotient.lift_mk,
        chartYtToNormalEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_neg (by decide), if_pos (by decide)]
      simp only [normalYtToChart, Ideal.Quotient.lift_mk, RingHom.comp_apply, normalYtToModel,
        MvPolynomial.eval₂Hom_X']
      rw [if_true]
      exact chartYt_fin4 2 ⟨2, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, chartYtToNormal, Ideal.Quotient.lift_mk,
        chartYtToNormalEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_neg (by decide), if_neg (by decide)]
      simp only [normalYtToChart, Ideal.Quotient.lift_mk, RingHom.comp_apply, normalYtToModel,
        MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide : (2 : Fin 3) ≠ 0), if_neg (by decide : (2 : Fin 3) ≠ 1)]
      exact chartYt_fin4 3 ⟨3, by decide⟩ rfl

/-- Eliminating `X` by `X = Y·S`. -/
noncomputable def modelYtChart_quotient_equiv_normal :
    modelYtChart ≃+* chartYtNormalRing :=
  RingEquiv.ofRingHom chartYtToNormal normalYtToChart
    chartYtToNormal_comp_normalYtToChart normalYtToChart_comp_chartYtToNormal

/-!
`D₊(Yt)` is the degree-zero chart at `Yt`. The centre is still `(2, X, Y)`,
so the integral Rees chart is generated by the three ratios against `Yt`.
No power of `Yt` dies in `Rees/(2)`, so the special chart is generated by
the same ratios. Those ratios are `T`, `S`, and `1`, and the surface
scalars are polynomials in the degree-zero classes `X` and `Y`.
-/

theorem valuationOne_X_residue_Y :
    valuationOne_X_residue
      (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
        (MvPolynomial.X (1 : Fin 2))) = 1 := by
  rw [valuationOne_X_residue, Ideal.Quotient.lift_mk, residuePointEval,
    MvPolynomial.eval₂Hom_X', if_neg (by decide : (1 : Fin 2) ≠ 0)]

/-- No power of the class of `Y t` vanishes in `Rees/(2)`. A relation
`(Y t)^n = 2 · p` would force `Y^n` to be divisible by `2`, but `Y`
survives as `1` in the residue field. -/
theorem valuationOne_specialYT_pow_ne_zero (n : ℕ) :
    (Ideal.Quotient.mk (numeralReesSpecialIdeal valuationOneCurve 0 0)
      (numeralReesYT valuationOneCurve 0 0)) ^ n ≠ 0 := by
  intro hzero
  let I := numeralCentreIdeal valuationOneCurve 0 0
  let R := surfaceRing valuationOneCurve
  have hmem : (numeralReesYT valuationOneCurve 0 0) ^ n ∈
      numeralReesSpecialIdeal valuationOneCurve 0 0 := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_pow]
    exact hzero
  obtain ⟨p, hp⟩ := Ideal.mem_span_singleton'.mp hmem
  let y : R := Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
    (MvPolynomial.X (1 : Fin 2))
  have hmono : ((numeralReesYT valuationOneCurve 0 0 : reesAlgebra I) : Polynomial R) =
      Polynomial.monomial 1 y := by
    simp [numeralReesYT, centreReesMonomial, y]
  have hpoly := congrArg (fun z : reesAlgebra I => (z : Polynomial R)) hp
  dsimp at hpoly
  rw [hmono, Polynomial.monomial_pow] at hpoly
  simp only [one_mul] at hpoly
  rw [mul_comm] at hpoly
  have hcoeff := congrArg (fun q : Polynomial R => q.coeff n) hpoly
  dsimp at hcoeff
  rw [Polynomial.coeff_C_mul, Polynomial.coeff_monomial, if_pos rfl] at hcoeff
  have hdiv : y ^ n = (2 : R) * (p : Polynomial R).coeff n := hcoeff.symm
  have hφ := congrArg valuationOne_X_residue hdiv
  rw [map_pow, valuationOne_X_residue_Y, map_mul, valuationOne_X_residue_two,
    zero_mul, one_pow] at hφ
  exact one_ne_zero hφ

section YtGeneration

private noncomputable def ytDenom : reesAlgebra nodeCentre :=
  centreReesDegreeOne nodeCentre (nodeGenerator 2) (nodeGenerator_mem 2)

example : ytDenom = numeralReesYT valuationOneCurve 0 0 := by
  rfl

noncomputable local instance ytReesAlgebra :
    Algebra nodeSurface (reesAlgebra nodeCentre) := inferInstance

noncomputable local instance ytQuotientAlgebra :
    Algebra nodeSurface ((reesAlgebra nodeCentre) ⧸ nodeSpecial) := inferInstance

noncomputable local instance ytReesGrading :
    GradedAlgebra (centreReesComponent nodeCentre) :=
  centreReesGrading nodeCentre

/-- `R[T₀,T₁,T₂] →` the integral chart at `Yt`. `T₀,T₁,T₂` are the
ratios of `2`, `X`, and `Y` against `Yt`. -/
noncomputable def ytIntegralRatio :
    MvPolynomial (Fin 3) nodeSurface →+*
      HomogeneousLocalization.Away (centreReesComponent nodeCentre) ytDenom :=
  centreReesRatioPolynomialMap nodeCentre nodeGenerator nodeGenerator_mem
    (nodeGenerator 2) (nodeGenerator_mem 2)

theorem ytIntegralRatio_surjective : Function.Surjective ytIntegralRatio :=
  centreReesRatioPolynomialMap_surjective nodeCentre nodeGenerator
    nodeGenerator_mem nodeCentre_eq_span (nodeGenerator 2) (nodeGenerator_mem 2)

noncomputable def ytSpecialAway :
    HomogeneousLocalization.Away (centreReesComponent nodeCentre) ytDenom →+*
      chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
  homogeneousQuotientAwayMap (centreReesComponent (R := nodeSurface) nodeCentre)
    nodeSpecial (numeralReesSpecialIdeal_isHomogeneous valuationOneCurve 0 0)
    ytDenom

theorem ytSpecialAway_surjective : Function.Surjective ytSpecialAway := by
  have hdeg : ytDenom ∈ centreReesComponent nodeCentre 1 :=
    centreReesDegreeOne_mem nodeCentre (nodeGenerator 2) (nodeGenerator_mem 2)
  have hpow : ∀ n : ℕ,
      (Ideal.Quotient.mk nodeSpecial ytDenom) ^ n ≠ 0 := by
    intro n
    simpa using valuationOne_specialYT_pow_ne_zero n
  simpa [ytSpecialAway] using
    homogeneousQuotientAwayMap_surjective
      (centreReesComponent (R := nodeSurface) nodeCentre) nodeSpecial
      (numeralReesSpecialIdeal_isHomogeneous valuationOneCurve 0 0)
      ytDenom 1 hdeg hpow

/-- Surface scalars and the three ratios generate `D₊(Yt)`. -/
noncomputable def ytChartRatio :
    MvPolynomial (Fin 3) nodeSurface →+*
      chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
  ytSpecialAway.comp ytIntegralRatio

theorem ytChartRatio_surjective : Function.Surjective ytChartRatio :=
  ytSpecialAway_surjective.comp ytIntegralRatio_surjective

private lemma ytIntegralRatio_C (r : nodeSurface) :
    ytIntegralRatio (MvPolynomial.C r) =
      homogeneousScalarAway (centreReesComponent nodeCentre) ytDenom r := by
  rw (config := { transparency := .default })
    [ytIntegralRatio, centreReesRatioPolynomialMap, MvPolynomial.eval₂Hom_C]
  rfl

theorem ytChartRatio_C (r : nodeSurface) :
    ytChartRatio (MvPolynomial.C r) = chartYtConst valuationOneCurve 0 0 r := by
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  rw [ytChartRatio, RingHom.comp_apply, ytIntegralRatio_C]
  rw (config := { transparency := .default })
    [ytSpecialAway, homogeneousQuotientAwayMap, homogeneousScalarAway,
      gradedLocalizationMap_mk]
  simp [chartYtConst, HomogeneousLocalization.val_mk, yt_numeralReesConst_eq_algebraMap]

private lemma ytIntegralRatio_X (i : Fin 3) :
    ytIntegralRatio (MvPolynomial.X i) =
      centreReesNormalizedFraction nodeCentre (nodeGenerator 2) (nodeGenerator_mem 2) 1
        (nodeGenerator i) (by simpa [pow_one] using nodeGenerator_mem i) := by
  rw (config := { transparency := .default })
    [ytIntegralRatio, centreReesRatioPolynomialMap, MvPolynomial.eval₂Hom_X']

/-- `2t / Yt`. -/
theorem ytChartRatio_X0 :
    ytChartRatio (MvPolynomial.X 0) = chartYt_two_over_Y valuationOneCurve 0 0 := by
  rw [ytChartRatio, RingHom.comp_apply, ytIntegralRatio_X]
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  simp only [ytSpecialAway, homogeneousQuotientAwayMap, centreReesNormalizedFraction,
    chartYt_two_over_Y, HomogeneousLocalization.val_mk, nodeGenerator, numeralReesTwo,
    centreReesMonomial, pow_one]
  delta gradedLocalizationMap
  conv_lhs => whnf
  rfl

/-- `Xt / Yt`. -/
theorem ytChartRatio_X1 :
    ytChartRatio (MvPolynomial.X 1) = chartYt_X_over_Y valuationOneCurve 0 0 := by
  rw [ytChartRatio, RingHom.comp_apply, ytIntegralRatio_X]
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  simp only [ytSpecialAway, homogeneousQuotientAwayMap, centreReesNormalizedFraction,
    chartYt_X_over_Y, HomogeneousLocalization.val_mk, nodeGenerator, numeralReesXT,
    centreReesMonomial, pow_one]
  delta gradedLocalizationMap
  conv_lhs => whnf
  rfl

/-- `Yt / Yt = 1`. -/
theorem ytChartRatio_X2 : ytChartRatio (MvPolynomial.X 2) = 1 := by
  rw [ytChartRatio, RingHom.comp_apply, ytIntegralRatio_X]
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  simp only [ytSpecialAway, homogeneousQuotientAwayMap, centreReesNormalizedFraction,
    HomogeneousLocalization.val_mk, HomogeneousLocalization.val_one, nodeGenerator,
    centreReesMonomial, pow_one]
  delta gradedLocalizationMap
  conv_lhs => whnf
  let y : (reesAlgebra nodeCentre) ⧸ nodeSpecial :=
    Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0)
  have hy : y ∈ M := ⟨1, pow_one y⟩
  change Localization.mk y ⟨y, hy⟩ = 1
  exact Localization.mk_self (⟨y, hy⟩ : M)

private lemma yt_coeffModTwoEquiv_mk (s : S) :
    coeffModTwoEquiv (Ideal.Quotient.mk (Ideal.span {MvPolynomial.C (2 : ℤ_[2])}) s) =
      MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2) s := by
  rw [coeffModTwoEquiv, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk,
    RingHom.quotientKerEquivOfSurjective, RingHom.quotientKerEquivOfRightInverse.apply,
    RingHom.kerLift_mk]

private lemma chartYtScalar_eq_fromF2 (c : S) :
    chartYtScalar valuationOneCurve 0 0 c =
      chartYtFromF2Polynomial valuationOneCurve 0 0
        (MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2) c) := by
  rw [chartYtFromF2Polynomial, RingHom.comp_apply]
  have heq :
      coeffModTwoEquiv.symm
          (MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2) c) =
        Ideal.Quotient.mk (Ideal.span {MvPolynomial.C (2 : ℤ_[2])}) c := by
    apply coeffModTwoEquiv.injective
    rw [coeffModTwoEquiv.apply_symm_apply, yt_coeffModTwoEquiv_mk]
  have hcoe :
      (coeffModTwoEquiv.symm.toRingHom)
          (MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2) c) =
        coeffModTwoEquiv.symm
          (MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2) c) := rfl
  rw [hcoe, heq, chartYtScalarModTwo, Ideal.Quotient.lift_mk]

private lemma chartYt_X_eq_const :
    chartYt_X valuationOneCurve 0 0 =
      chartYtConst valuationOneCurve 0 0
        (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
          (MvPolynomial.X 0)) := by
  have hX : surfaceNumeralX valuationOneCurve 0 =
      Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
        (MvPolynomial.X 0) := by
    simp [surfaceNumeralX, sub_zero]
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  simp [chartYt_X, chartYtConst, HomogeneousLocalization.val_mk, hX, numeralReesConst]

private lemma chartYt_Y_eq_const :
    chartYt_Y valuationOneCurve 0 0 =
      chartYtConst valuationOneCurve 0 0
        (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
          (MvPolynomial.X 1)) := by
  have hY : surfaceNumeralY valuationOneCurve 0 =
      Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
        (MvPolynomial.X 1) := by
    simp [surfaceNumeralY, sub_zero]
  let M := Submonoid.powers
    (Ideal.Quotient.mk nodeSpecial (numeralReesYT valuationOneCurve 0 0))
  apply HomogeneousLocalization.val_injective M
  simp [chartYt_Y, chartYtConst, HomogeneousLocalization.val_mk, hY, numeralReesConst]

private lemma chartYtModelEval_embed_X (i : Fin 2) :
    chartYtModelEval (embedXY (MvPolynomial.X i)) =
      chartYtConst valuationOneCurve 0 0
        (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
          (MvPolynomial.X i)) := by
  fin_cases i
  · have hcast : (Fin.castAdd 2 (0 : Fin 2) : Fin 4) = 0 := rfl
    simp [embedXY, chartYtModelEval, hcast, chartYt_X_eq_const]
  · have hcast : (Fin.castAdd 2 (1 : Fin 2) : Fin 4) = 1 := rfl
    simp [embedXY, chartYtModelEval, hcast, chartYt_Y_eq_const]

theorem chartYtConst_mk_polynomial (q : MvPolynomial (Fin 2) S) :
    chartYtConst valuationOneCurve 0 0
        (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve}) q) =
      chartYtModelEval (embedXY (coeffToF2 q)) := by
  let φ : MvPolynomial (Fin 2) S →+*
      chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
    (chartYtConstHom valuationOneCurve 0 0).comp
      (Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve}))
  let ψ : MvPolynomial (Fin 2) S →+*
      chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
    chartYtModelEval.comp
      (((MvPolynomial.rename (Fin.castAdd 2)).toRingHom).comp
        (MvPolynomial.map (MvPolynomial.map (PadicInt.toZMod : ℤ_[2] →+* ZMod 2))))
  have hφψ : φ = ψ := by
    apply MvPolynomial.ringHom_ext
    · intro c
      simp only [φ, ψ, RingHom.comp_apply, coeffToF2, embedXY, MvPolynomial.map_C,
        MvPolynomial.rename_C, chartYtModelEval, MvPolynomial.eval₂Hom_C]
      have hmk : Ideal.Quotient.mk (Ideal.span {surfacePolynomial valuationOneCurve})
          (MvPolynomial.C c) = algebraMap S nodeSurface c := by
        rw [IsScalarTower.algebraMap_apply S (MvPolynomial (Fin 2) S) nodeSurface,
          MvPolynomial.algebraMap_eq, Ideal.Quotient.algebraMap_eq]
      rw [hmk]
      change (chartYtScalar valuationOneCurve 0 0) c = _
      rw [chartYtScalar_eq_fromF2]
      rw (config := { transparency := .default })
        [MvPolynomial.rename_C, MvPolynomial.eval₂Hom_C]
    · intro i
      simp only [φ, ψ, RingHom.comp_apply, MvPolynomial.map_X, MvPolynomial.rename_X]
      exact (chartYtModelEval_embed_X i).symm
  simpa [φ, ψ, coeffToF2, embedXY] using congrFun (congrArg DFunLike.coe hφψ) q

theorem ytChartRatio_mem_model (q : MvPolynomial (Fin 3) nodeSurface) :
    ∃ p : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)),
      chartYtModelEval p = ytChartRatio q := by
  induction q using MvPolynomial.induction_on with
  | h_C r =>
      obtain ⟨poly, rfl⟩ :=
        Ideal.Quotient.mk_surjective (I := Ideal.span {surfacePolynomial valuationOneCurve}) r
      refine ⟨embedXY (coeffToF2 poly), ?_⟩
      rw [ytChartRatio_C, chartYtConst_mk_polynomial]
  | h_add p q hp hq =>
      obtain ⟨p', hp'⟩ := hp
      obtain ⟨q', hq'⟩ := hq
      refine ⟨p' + q', ?_⟩
      rw [map_add, map_add, hp', hq']
  | h_X p i hp =>
      obtain ⟨p', hp'⟩ := hp
      fin_cases i
      · refine ⟨p' * MvPolynomial.X 3, ?_⟩
        rw [map_mul, hp', map_mul]
        rw (config := { transparency := .default }) [ytChartRatio_X0, chartYtModelEval_X]
        simp
      · refine ⟨p' * MvPolynomial.X 2, ?_⟩
        rw [map_mul, hp', map_mul]
        rw (config := { transparency := .default }) [ytChartRatio_X1, chartYtModelEval_X]
        simp
      · refine ⟨p', ?_⟩
        rw [map_mul]
        rw (config := { transparency := .default }) [ytChartRatio_X2]
        rw [mul_one, hp']

theorem chartYtModelEval_surjective : Function.Surjective chartYtModelEval := by
  intro z
  obtain ⟨q, rfl⟩ := ytChartRatio_surjective z
  obtain ⟨p, hp⟩ := ytChartRatio_mem_model q
  exact ⟨p, hp⟩

/-- `Y`, `S = Xt/Yt`, and `T = 2t/Yt` generate `D₊(Yt)`, and `X = Y·S`. -/
theorem chartOfModelTrueY_surjective : Function.Surjective chartOfModelTrueY := by
  intro z
  obtain ⟨p, hp⟩ := chartYtModelEval_surjective z
  refine ⟨Ideal.Quotient.mk modelYtTrueIdeal p, ?_⟩
  rw [chartOfModelTrueY, Ideal.Quotient.lift_mk]
  exact hp

end YtGeneration

/-!
`T + Y + Y²·S³` dies in `D₊(Yt)` and is not in `modelYtTrueIdeal`.
`Y·T = 0` and `T² = 0` do not split `p(Y,S) + T·B(S)` in the chart:
`T` is a zerodivisor, and the missing relation identifies `T` with
`Y + Y²·S³`.
-/

private lemma valuationOne_two_eq_Xcu_sub_Ysq :
    (2 : surfaceRing valuationOneCurve) =
      surfaceNumeralX valuationOneCurve 0 ^ 3 -
        surfaceNumeralY valuationOneCurve 0 ^ 2 := by
  have h := valuationOne_node_Ysq_sub_Xcu
  calc
    (2 : surfaceRing valuationOneCurve) =
        -(-(2 : surfaceRing valuationOneCurve)) := by ring
    _ = -(surfaceNumeralY valuationOneCurve 0 ^ 2 -
        surfaceNumeralX valuationOneCurve 0 ^ 3) := by rw [← h]
    _ = surfaceNumeralX valuationOneCurve 0 ^ 3 -
        surfaceNumeralY valuationOneCurve 0 ^ 2 := by ring

private lemma valuationOne_reesTwo_split :
    numeralReesTwo valuationOneCurve 0 0 =
      numeralReesConst valuationOneCurve 0 0
          (surfaceNumeralX valuationOneCurve 0 ^ 2) *
        numeralReesXT valuationOneCurve 0 0 -
      numeralReesConst valuationOneCurve 0 0
          (surfaceNumeralY valuationOneCurve 0) *
        numeralReesYT valuationOneCurve 0 0 := by
  let I := numeralCentreIdeal valuationOneCurve 0 0
  let R := surfaceRing valuationOneCurve
  let x := surfaceNumeralX valuationOneCurve 0
  let y := surfaceNumeralY valuationOneCurve 0
  apply Subtype.ext
  have h2coe : ((numeralReesTwo valuationOneCurve 0 0 : reesAlgebra I) : Polynomial R) =
      Polynomial.monomial 1 (2 : R) := rfl
  have hx2coe :
      ((numeralReesConst valuationOneCurve 0 0 (x ^ 2) : reesAlgebra I) : Polynomial R) =
        Polynomial.monomial 0 (x ^ 2) := rfl
  have hxcoe : ((numeralReesXT valuationOneCurve 0 0 : reesAlgebra I) : Polynomial R) =
      Polynomial.monomial 1 x := rfl
  have hy0coe : ((numeralReesConst valuationOneCurve 0 0 y : reesAlgebra I) : Polynomial R) =
      Polynomial.monomial 0 y := rfl
  have hycoe : ((numeralReesYT valuationOneCurve 0 0 : reesAlgebra I) : Polynomial R) =
      Polynomial.monomial 1 y := rfl
  rw [Subalgebra.coe_sub, Subalgebra.coe_mul, Subalgebra.coe_mul, h2coe, hx2coe, hxcoe, hy0coe,
    hycoe]
  rw [Polynomial.monomial_mul_monomial, Polynomial.monomial_mul_monomial, zero_add]
  rw [← map_sub (Polynomial.monomial 1)]
  congr 1
  symm
  calc
    x ^ 2 * x - y * y = x ^ 3 - y ^ 2 := by ring
    _ = (2 : R) := valuationOne_two_eq_Xcu_sub_Ysq.symm

/-- `2t · Yt² + C(Y) · Yt³ − C(Y)² · Xt³ = 0` in the integral Rees algebra. -/
private lemma valuationOne_yt_kernel_integral :
    numeralReesTwo valuationOneCurve 0 0 *
        (numeralReesYT valuationOneCurve 0 0) ^ 2 +
      numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0) *
        (numeralReesYT valuationOneCurve 0 0) ^ 3 -
      (numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0)) ^ 2 *
        (numeralReesXT valuationOneCurve 0 0) ^ 3 = 0 := by
  let x := surfaceNumeralX valuationOneCurve 0
  let y := surfaceNumeralY valuationOneCurve 0
  set two := numeralReesTwo valuationOneCurve 0 0
  set xt := numeralReesXT valuationOneCurve 0 0
  set yt := numeralReesYT valuationOneCurve 0 0
  set cy := numeralReesConst valuationOneCurve 0 0 y
  set cx := numeralReesConst valuationOneCurve 0 0 x
  set cx2 := numeralReesConst valuationOneCurve 0 0 (x ^ 2)
  have hsplit : two = cx2 * xt - cy * yt := valuationOne_reesTwo_split
  have hcomm : yt * cx = cy * xt :=
    yt_mul_const_X_eq_const_Y_mul_xt valuationOneCurve 0 0
  have hcx : cx * cx = cx2 := by
    apply Subtype.ext
    simp only [cx, cx2]
    unfold numeralReesConst centreReesMonomial
    rw [Subalgebra.coe_mul]
    dsimp
    rw [← Polynomial.C_mul]
    exact congrArg Polynomial.C (pow_two x).symm
  have hcross : cx2 * xt * yt ^ 2 = (cy * cy) * xt ^ 3 := by
    calc
      cx2 * xt * yt ^ 2 = (cx * cx) * xt * yt ^ 2 := by rw [← hcx]
      _ = (yt * cx) ^ 2 * xt := by ring
      _ = (cy * xt) ^ 2 * xt := by rw [hcomm]
      _ = (cy * cy) * xt ^ 3 := by ring
  have hscaled : two * yt ^ 2 = (cy * cy) * xt ^ 3 - cy * yt ^ 3 := by
    rw [hsplit]
    calc
      (cx2 * xt - cy * yt) * yt ^ 2 =
          cx2 * xt * yt ^ 2 - cy * yt * yt ^ 2 := by ring
      _ = (cy * cy) * xt ^ 3 - cy * yt ^ 3 := by
        rw [hcross]
        ring
  rw [pow_two cy]
  rw [hscaled]
  ring

/-- The same numerator with the sign of `C(Y)² · Xt³` flipped lies in `(2)`,
because `2 = 0` on the special fibre. -/
private lemma valuationOne_yt_kernel_plus_mem_special :
    numeralReesTwo valuationOneCurve 0 0 *
        (numeralReesYT valuationOneCurve 0 0) ^ 2 +
      numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0) *
        (numeralReesYT valuationOneCurve 0 0) ^ 3 +
      (numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0)) ^ 2 *
        (numeralReesXT valuationOneCurve 0 0) ^ 3 ∈
      numeralReesSpecialIdeal valuationOneCurve 0 0 := by
  let I := numeralCentreIdeal valuationOneCurve 0 0
  let y := surfaceNumeralY valuationOneCurve 0
  let cy := numeralReesConst valuationOneCurve 0 0 y
  let yt := numeralReesYT valuationOneCurve 0 0
  let xt := numeralReesXT valuationOneCurve 0 0
  let two := numeralReesTwo valuationOneCurve 0 0
  let extra := cy ^ 2 * xt ^ 3
  have hsigned :
      two * yt ^ 2 + cy * yt ^ 3 - cy ^ 2 * xt ^ 3 = 0 :=
    valuationOne_yt_kernel_integral
  have hsum :
      two * yt ^ 2 + cy * yt ^ 3 + cy ^ 2 * xt ^ 3 =
        (two * yt ^ 2 + cy * yt ^ 3 - cy ^ 2 * xt ^ 3) + (extra + extra) := by
    simp only [extra]
    ring
  rw [hsum, hsigned, zero_add, ← two_mul]
  have hnat :
      (2 : reesAlgebra I) =
        algebraMap (surfaceRing valuationOneCurve) (reesAlgebra I)
          (2 : surfaceRing valuationOneCurve) :=
    (map_natCast (algebraMap (surfaceRing valuationOneCurve) (reesAlgebra I)) 2).symm
  rw [hnat]
  exact Ideal.mul_mem_right _ _
    (Ideal.mem_span_singleton_self
      (algebraMap (surfaceRing valuationOneCurve) (reesAlgebra I)
        (2 : surfaceRing valuationOneCurve)))

/-- `2t/Yt + Y + Y² · (Xt/Yt)³ = 0` on `D₊(Yt)`. -/
theorem chartYt_kernel_relation :
    chartYt_two_over_Y valuationOneCurve 0 0 +
      chartYt_Y valuationOneCurve 0 0 +
      chartYt_Y valuationOneCurve 0 0 ^ 2 *
        chartYt_X_over_Y valuationOneCurve 0 0 ^ 3 = 0 := by
  let I := numeralCentreIdeal valuationOneCurve 0 0
  letI : GradedAlgebra (centreReesComponent I) := centreReesGrading I
  let J := numeralReesSpecialIdeal valuationOneCurve 0 0
  have hJ : J.IsHomogeneous (centreReesComponent I) :=
    numeralReesSpecialIdeal_isHomogeneous valuationOneCurve 0 0
  let ℬ := homogeneousQuotientComponent (centreReesComponent I) J
  letI : GradedAlgebra ℬ := homogeneousQuotientGrading (centreReesComponent I) J hJ
  let Q := (reesAlgebra I) ⧸ J
  let f : Q := Ideal.Quotient.mk J (numeralReesYT valuationOneCurve 0 0)
  let nx : Q := Ideal.Quotient.mk J (numeralReesXT valuationOneCurve 0 0)
  let ny : Q := Ideal.Quotient.mk J
    (numeralReesConst valuationOneCurve 0 0 (surfaceNumeralY valuationOneCurve 0))
  let n2 : Q := Ideal.Quotient.mk J (numeralReesTwo valuationOneCurve 0 0)
  apply HomogeneousLocalization.val_injective (Submonoid.powers f)
  erw [HomogeneousLocalization.val_add, HomogeneousLocalization.val_add,
    HomogeneousLocalization.val_mul, HomogeneousLocalization.val_pow,
    HomogeneousLocalization.val_pow, HomogeneousLocalization.val_zero]
  simp only [chartYt_two_over_Y, chartYt_Y, chartYt_X_over_Y,
    HomogeneousLocalization.val_mk]
  let d0 : Submonoid.powers f := ⟨(1 : Q), ⟨0, pow_zero f⟩⟩
  let d1 : Submonoid.powers f := ⟨f, ⟨1, pow_one f⟩⟩
  let d3 : Submonoid.powers f := ⟨f ^ 3, ⟨3, rfl⟩⟩
  have hd0 : (⟨(1 : Q), ⟨0, pow_zero f⟩⟩ : Submonoid.powers f) = d0 := rfl
  have hd1 : (⟨f, ⟨1, pow_one f⟩⟩ : Submonoid.powers f) = d1 := rfl
  have hden : d0 ^ 2 * d1 ^ 3 = d3 := by
    apply Subtype.ext
    simp [d0, d1, d3]
    ring
  rw [hd0, hd1]
  rw [Localization.mk_pow, Localization.mk_pow, Localization.mk_mul]
  rw [hden]
  have hT : Localization.mk n2 d1 = Localization.mk (n2 * f ^ 2) d3 := by
    rw [Localization.mk_eq_mk_iff]
    refine Localization.r_iff_exists.mpr ⟨1, ?_⟩
    simp [d1, d3]
    ring
  have hY : Localization.mk ny d0 = Localization.mk (ny * f ^ 3) d3 := by
    rw [Localization.mk_eq_mk_iff]
    refine Localization.r_iff_exists.mpr ⟨1, ?_⟩
    simp [d0, d3]
    ring
  rw [hT, hY]
  have hnum : n2 * f ^ 2 + ny * f ^ 3 + ny ^ 2 * nx ^ 3 = 0 := by
    have hpush :
        n2 * f ^ 2 + ny * f ^ 3 + ny ^ 2 * nx ^ 3 =
          Ideal.Quotient.mk J
            (numeralReesTwo valuationOneCurve 0 0 *
                (numeralReesYT valuationOneCurve 0 0) ^ 2 +
              numeralReesConst valuationOneCurve 0 0
                  (surfaceNumeralY valuationOneCurve 0) *
                (numeralReesYT valuationOneCurve 0 0) ^ 3 +
              (numeralReesConst valuationOneCurve 0 0
                  (surfaceNumeralY valuationOneCurve 0)) ^ 2 *
                (numeralReesXT valuationOneCurve 0 0) ^ 3) := by
      simp only [n2, ny, nx, f, ← map_mul, ← map_pow, ← map_add]
    rw [hpush]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr valuationOne_yt_kernel_plus_mem_special
  have hAB := Localization.add_mk_self (n2 * f ^ 2) d3 (ny * f ^ 3)
  have hABC := Localization.add_mk_self
    (n2 * f ^ 2 + ny * f ^ 3) d3 (ny ^ 2 * nx ^ 3)
  erw [hAB, hABC, hnum]
  exact Localization.mk_zero d3

/-- `T + Y + Y²·S³` in `𝔽₂[a,b][X,Y,S,T]`. -/
noncomputable def chartYtKernelWitness :
    MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) :=
  MvPolynomial.X 3 + MvPolynomial.X 1 +
    (MvPolynomial.X 1) ^ 2 * (MvPolynomial.X 2) ^ 3

/-- `chartYtModelEval (T + Y + Y²·S³) = 0`. -/
theorem chartYtModelEval_kernelWitness :
    chartYtModelEval chartYtKernelWitness = 0 := by
  rw [chartYtKernelWitness]
  simp only [map_add, map_mul, map_pow, chartYtModelEval, MvPolynomial.eval₂Hom_X',
    if_neg (by decide : (3 : Fin 4) ≠ 0),
    if_neg (by decide : (3 : Fin 4) ≠ 1),
    if_neg (by decide : (3 : Fin 4) ≠ 2),
    if_neg (by decide : (1 : Fin 4) ≠ 0),
    if_pos (rfl : (1 : Fin 4) = 1),
    if_neg (by decide : (2 : Fin 4) ≠ 0),
    if_neg (by decide : (2 : Fin 4) ≠ 1),
    if_pos (rfl : (2 : Fin 4) = 2), if_true]
  exact chartYt_kernel_relation

/-- Send `T` to `ε` and `a, b, X, Y, S` to `0` in `𝔽₂[ε]`. -/
noncomputable def chartYtKernelWitnessDual :
    MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) →+*
      DualNumber (ZMod 2) :=
  MvPolynomial.eval₂Hom
    ((algebraMap (ZMod 2) (DualNumber (ZMod 2))).comp
      (MvPolynomial.eval₂Hom (RingHom.id (ZMod 2)) fun _ : Fin 2 => (0 : ZMod 2)))
    fun i : Fin 4 => if i = 3 then (DualNumber.eps : DualNumber (ZMod 2)) else 0

private lemma chartYtKernelWitnessDual_X (i : Fin 4) :
    chartYtKernelWitnessDual (MvPolynomial.X i) =
      if i = 3 then (DualNumber.eps : DualNumber (ZMod 2)) else 0 := by
  simp [chartYtKernelWitnessDual]

private lemma chartYtKernelWitnessDual_eps_ne_zero :
    (DualNumber.eps : DualNumber (ZMod 2)) ≠ 0 := by
  intro h
  have hsnd := congrArg TrivSqZeroExt.snd h
  simp at hsnd

private lemma chartYtKernelWitnessDual_apply :
    chartYtKernelWitnessDual chartYtKernelWitness = DualNumber.eps := by
  simp [chartYtKernelWitness, map_add, map_mul, map_pow, chartYtKernelWitnessDual_X,
    if_neg (by decide : (1 : Fin 4) ≠ 3),
    if_neg (by decide : (2 : Fin 4) ≠ 3),
    if_pos (rfl : (3 : Fin 4) = 3)]

/-- `T + Y + Y²·S³` is outside `(X − Y·S, Y²·(1 − Y·S³), Y·T, T²)`. -/
theorem chartYtKernelWitness_not_mem :
    chartYtKernelWitness ∉ modelYtTrueIdeal := by
  intro hmem
  have hker : modelYtTrueIdeal ≤ RingHom.ker chartYtKernelWitnessDual := by
    rw [modelYtTrueIdeal, Ideal.span_le]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl | rfl | rfl
    · rw [SetLike.mem_coe, RingHom.mem_ker, map_sub, map_mul, chartYtKernelWitnessDual_X,
        chartYtKernelWitnessDual_X, chartYtKernelWitnessDual_X,
        if_neg (by decide : (0 : Fin 4) ≠ 3),
        if_neg (by decide : (1 : Fin 4) ≠ 3),
        if_neg (by decide : (2 : Fin 4) ≠ 3)]
      simp
    · simp [RingHom.mem_ker, map_mul, map_pow, map_sub, map_one, chartYtKernelWitnessDual_X,
        if_neg (by decide : (1 : Fin 4) ≠ 3),
        if_neg (by decide : (2 : Fin 4) ≠ 3)]
    · rw [SetLike.mem_coe, RingHom.mem_ker, map_mul, chartYtKernelWitnessDual_X,
        chartYtKernelWitnessDual_X,
        if_neg (by decide : (1 : Fin 4) ≠ 3),
        if_pos (rfl : (3 : Fin 4) = 3)]
      simp
    · simp [RingHom.mem_ker, map_pow, chartYtKernelWitnessDual_X, pow_two,
        DualNumber.eps_mul_eps,
        if_pos (rfl : (3 : Fin 4) = 3)]
  have hzero : chartYtKernelWitnessDual chartYtKernelWitness = 0 :=
    RingHom.mem_ker.mp (hker hmem)
  rw [chartYtKernelWitnessDual_apply] at hzero
  exact chartYtKernelWitnessDual_eps_ne_zero hzero

/-- `𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal → D₊(Yt)` is not injective.
`T + Y + Y²·S³` is a nonzero class sent to zero. -/
theorem not_chartOfModelTrueY_injective : ¬ Function.Injective chartOfModelTrueY := by
  intro hinj
  have hzero : chartOfModelTrueY
      (Ideal.Quotient.mk modelYtTrueIdeal chartYtKernelWitness) =
      chartOfModelTrueY 0 := by
    rw [map_zero]
    simpa [chartOfModelTrueY] using chartYtModelEval_kernelWitness
  have heq := hinj hzero
  have hmem : chartYtKernelWitness ∈ modelYtTrueIdeal :=
    Ideal.Quotient.eq_zero_iff_mem.mp heq
  exact chartYtKernelWitness_not_mem hmem

/-!
The relation `T + Y + Y²·S³ = 0` is the missing generator. With it,
`Y·T` and `T²` are redundant, and both `X` and `T` eliminate.
-/

/-- `(X − Y·S, T + Y + Y²·S³, Y²·(1 − Y·S³))` in `𝔽₂[a,b][X,Y,S,T]`. -/
noncomputable def modelYtTrueIdeal_fixed :
    Ideal (MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2))) :=
  Ideal.span {
    MvPolynomial.X 0 - MvPolynomial.X 1 * MvPolynomial.X 2,
    MvPolynomial.X 3 + MvPolynomial.X 1 +
      (MvPolynomial.X 1) ^ 2 * (MvPolynomial.X 2) ^ 3,
    (MvPolynomial.X 1) ^ 2 * (1 - MvPolynomial.X 1 * (MvPolynomial.X 2) ^ 3) }

/-- `𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal_fixed`. -/
abbrev modelYtChart_fixed : Type :=
  MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) ⧸ modelYtTrueIdeal_fixed

private lemma modelYt_fixed_witness_mem :
    MvPolynomial.X (3 : Fin 4) + MvPolynomial.X 1 +
        (MvPolynomial.X 1) ^ 2 * (MvPolynomial.X 2) ^ 3 ∈
      modelYtTrueIdeal_fixed := by
  rw [modelYtTrueIdeal_fixed]
  exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_insert _ _))

private lemma modelYt_fixed_cusp_mem :
    (MvPolynomial.X (1 : Fin 4)) ^ 2 *
        (1 - MvPolynomial.X 1 * (MvPolynomial.X 2) ^ 3) ∈
      modelYtTrueIdeal_fixed := by
  rw [modelYtTrueIdeal_fixed]
  exact Ideal.subset_span
    (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ (Set.mem_singleton _)))

/-- `Y·T` is redundant: `Y·T = Y·(T + Y + Y²·S³) + Y²·(1 − Y·S³)`. -/
theorem modelYtTrueIdeal_fixed_mem_mul_YT :
    MvPolynomial.X (1 : Fin 4) * MvPolynomial.X 3 ∈ modelYtTrueIdeal_fixed := by
  let y : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 1
  let s : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 2
  let t : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 3
  let cusp := y ^ 2 * (1 - y * s ^ 3)
  let witness := t + y + y ^ 2 * s ^ 3
  have hpoly :
      y * t + (y * (t + y + y ^ 2 * s ^ 3) + y ^ 2 * (1 + y * s ^ 3)) =
        (y * t + y * t) + (y ^ 2 + y ^ 2) + (y ^ 3 * s ^ 3 + y ^ 3 * s ^ 3) := by
    ring
  have hyt : y * t = y * witness + cusp := by
    have hsum : y * t + (y * witness + cusp) = 0 := by
      simp only [witness, cusp, CharTwo.sub_eq_add, hpoly]
      rw [CharTwo.add_self_eq_zero (y * t), CharTwo.add_self_eq_zero (y ^ 2),
        CharTwo.add_self_eq_zero (y ^ 3 * s ^ 3), add_zero, add_zero]
    have hneg := eq_neg_of_add_eq_zero_left hsum
    rwa [CharTwo.neg_eq] at hneg
  rw [hyt]
  exact Ideal.add_mem _ (Ideal.mul_mem_left _ y modelYt_fixed_witness_mem)
    modelYt_fixed_cusp_mem

/-- `T²` is redundant. In characteristic 2,
`(Y + Y²·S³)² = (1 + Y·S³) · Y²·(1 − Y·S³)`. -/
theorem modelYtTrueIdeal_fixed_mem_Tsq :
    (MvPolynomial.X (3 : Fin 4)) ^ 2 ∈ modelYtTrueIdeal_fixed := by
  let y : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 1
  let s : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 2
  let t : MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) := MvPolynomial.X 3
  let cusp := y ^ 2 * (1 - y * s ^ 3)
  let witness := t + y + y ^ 2 * s ^ 3
  have hsq : (y + y ^ 2 * s ^ 3) ^ 2 = y ^ 2 * (1 + y * s ^ 3) ^ 2 := by
    rw [CharTwo.add_sq, CharTwo.add_sq, mul_pow]
    ring
  have hsq' : (y + y ^ 2 * s ^ 3) ^ 2 = (1 + y * s ^ 3) * cusp := by
    rw [hsq]
    simp only [cusp, CharTwo.sub_eq_add]
    ring
  have hwit : witness = t + (y + y ^ 2 * s ^ 3) := by
    simp only [witness, ← add_assoc]
  have ht2 : t ^ 2 = witness ^ 2 + (y + y ^ 2 * s ^ 3) ^ 2 := by
    have h := CharTwo.add_sq t (y + y ^ 2 * s ^ 3)
    rw [← hwit] at h
    have hsum : t ^ 2 + (witness ^ 2 + (y + y ^ 2 * s ^ 3) ^ 2) = 0 := by
      rw [h, add_assoc, CharTwo.add_self_eq_zero ((y + y ^ 2 * s ^ 3) ^ 2), add_zero,
        CharTwo.add_self_eq_zero (t ^ 2)]
    have hneg := eq_neg_of_add_eq_zero_left hsum
    rwa [CharTwo.neg_eq] at hneg
  rw [ht2, hsq']
  refine Ideal.add_mem _ ?_ (Ideal.mul_mem_left _ (1 + y * s ^ 3) modelYt_fixed_cusp_mem)
  rw [pow_two]
  apply Ideal.mul_mem_left
  exact modelYt_fixed_witness_mem

/-- `𝔽₂[a,b][Y,S] / (Y²·(1 − Y·S³))`. `0` is `Y`, `1` is `S`. -/
abbrev chartYtCuspPoly : Type :=
  MvPolynomial (Fin 2) (MvPolynomial (Fin 2) (ZMod 2))

noncomputable def chartYtCuspRel : chartYtCuspPoly :=
  (MvPolynomial.X 0) ^ 2 * (1 - MvPolynomial.X 0 * (MvPolynomial.X 1) ^ 3)

noncomputable def chartYtCuspIdeal : Ideal chartYtCuspPoly :=
  Ideal.span {chartYtCuspRel}

abbrev chartYtCuspRing : Type := chartYtCuspPoly ⧸ chartYtCuspIdeal

/-- Send `X, Y, S, T` to `Y·S, Y, S, Y + Y²·S³`. -/
noncomputable def closedYtToCuspEval :
    MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) →+* chartYtCuspRing :=
  MvPolynomial.eval₂Hom
    ((Ideal.Quotient.mk chartYtCuspIdeal).comp MvPolynomial.C)
    (fun i : Fin 4 =>
      if i = 0 then
        Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 0 * MvPolynomial.X 1)
      else if i = 1 then Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 0)
      else if i = 2 then Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 1)
      else Ideal.Quotient.mk chartYtCuspIdeal
        (MvPolynomial.X 0 + (MvPolynomial.X 0) ^ 2 * (MvPolynomial.X 1) ^ 3))

private lemma closedYtToCusp_X (i : Fin 4) :
    closedYtToCuspEval (MvPolynomial.X i) =
      if i = 0 then
        Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 0 * MvPolynomial.X 1)
      else if i = 1 then Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 0)
      else if i = 2 then Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X 1)
      else Ideal.Quotient.mk chartYtCuspIdeal
        (MvPolynomial.X 0 + (MvPolynomial.X 0) ^ 2 * (MvPolynomial.X 1) ^ 3) := by
  simp [closedYtToCuspEval, MvPolynomial.eval₂Hom_X']

theorem closedYtToCuspEval_kills :
    modelYtTrueIdeal_fixed ≤ RingHom.ker closedYtToCuspEval := by
  rw [modelYtTrueIdeal_fixed, Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl
  · rw [CharTwo.sub_eq_add, SetLike.mem_coe, RingHom.mem_ker, map_add, map_mul,
      closedYtToCusp_X, closedYtToCusp_X, closedYtToCusp_X,
      if_pos (rfl : (0 : Fin 4) = 0),
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    rw [map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      CharTwo.add_self_eq_zero, map_zero]
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_add, map_add, map_mul, map_pow, map_pow,
      closedYtToCusp_X, closedYtToCusp_X, closedYtToCusp_X,
      if_neg (by decide : (3 : Fin 4) ≠ 0),
      if_neg (by decide : (3 : Fin 4) ≠ 1),
      if_neg (by decide : (3 : Fin 4) ≠ 2),
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    rw [map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      add_assoc, CharTwo.add_self_eq_zero, map_zero]
  · rw [CharTwo.sub_eq_add, SetLike.mem_coe, RingHom.mem_ker, map_mul, map_pow, map_add,
      map_one, map_mul, map_pow, closedYtToCusp_X, closedYtToCusp_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    rw [← map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_pow (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_one (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_add (Ideal.Quotient.mk chartYtCuspIdeal),
      ← map_mul (Ideal.Quotient.mk chartYtCuspIdeal),
      ← CharTwo.sub_eq_add, Ideal.Quotient.eq_zero_iff_mem]
    rw [chartYtCuspIdeal, chartYtCuspRel]
    exact Ideal.subset_span (Set.mem_singleton _)

noncomputable def closedYtToCusp : modelYtChart_fixed →+* chartYtCuspRing :=
  Ideal.Quotient.lift modelYtTrueIdeal_fixed closedYtToCuspEval closedYtToCuspEval_kills

/-- Include `Y, S` as variables `1, 2`. -/
noncomputable def cuspYtToClosedPoly :
    chartYtCuspPoly →+* MvPolynomial (Fin 4) (MvPolynomial (Fin 2) (ZMod 2)) :=
  MvPolynomial.eval₂Hom MvPolynomial.C
    (fun i : Fin 2 => if i = 0 then MvPolynomial.X 1 else MvPolynomial.X 2)

private lemma cuspYtToClosed_rel :
    cuspYtToClosedPoly chartYtCuspRel =
      (MvPolynomial.X (1 : Fin 4)) ^ 2 *
        (1 - MvPolynomial.X 1 * (MvPolynomial.X 2) ^ 3) := by
  rw [chartYtCuspRel, CharTwo.sub_eq_add, cuspYtToClosedPoly, map_mul, map_pow, map_add,
    map_one, map_mul, map_pow, MvPolynomial.eval₂Hom_X', MvPolynomial.eval₂Hom_X',
    if_pos (rfl : (0 : Fin 2) = 0),
    if_neg (by decide : (1 : Fin 2) ≠ 0),
    ← CharTwo.sub_eq_add]

theorem cuspYtToClosed_kills :
    chartYtCuspIdeal ≤
      RingHom.ker ((Ideal.Quotient.mk modelYtTrueIdeal_fixed).comp cuspYtToClosedPoly) := by
  rw [chartYtCuspIdeal, Ideal.span_le]
  intro z hz
  rw [Set.mem_singleton_iff] at hz
  subst hz
  rw [SetLike.mem_coe, RingHom.mem_ker, RingHom.comp_apply, cuspYtToClosed_rel,
    Ideal.Quotient.eq_zero_iff_mem]
  exact modelYt_fixed_cusp_mem

noncomputable def cuspYtToClosed : chartYtCuspRing →+* modelYtChart_fixed :=
  Ideal.Quotient.lift chartYtCuspIdeal
    ((Ideal.Quotient.mk modelYtTrueIdeal_fixed).comp cuspYtToClosedPoly) cuspYtToClosed_kills

private lemma chartYt_fin4_fixed (i j : Fin 4) (h : i.val = j.val) :
    Ideal.Quotient.mk modelYtTrueIdeal_fixed (MvPolynomial.X i) =
      Ideal.Quotient.mk modelYtTrueIdeal_fixed (MvPolynomial.X j) :=
  congrArg (fun k : Fin 4 => Ideal.Quotient.mk modelYtTrueIdeal_fixed (MvPolynomial.X k))
    (Fin.ext h)

private lemma chartYt_fin2 (i j : Fin 2) (h : i.val = j.val) :
    Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X i) =
      Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X j) :=
  congrArg (fun k : Fin 2 => Ideal.Quotient.mk chartYtCuspIdeal (MvPolynomial.X k))
    (Fin.ext h)

private lemma closedYtToCusp_comp_cuspYtToClosed :
    closedYtToCusp.comp cuspYtToClosed = RingHom.id chartYtCuspRing := by
  apply Ideal.Quotient.ringHom_ext
  apply MvPolynomial.ringHom_ext
  · intro r
    simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, closedYtToCuspEval,
      cuspYtToClosed, cuspYtToClosedPoly, Ideal.Quotient.lift_mk, MvPolynomial.eval₂Hom_C]
  · intro i
    fin_cases i
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, cuspYtToClosed,
        Ideal.Quotient.lift_mk, closedYtToCuspEval, cuspYtToClosedPoly,
        MvPolynomial.eval₂Hom_X']
      rw [if_pos (by decide), MvPolynomial.eval₂Hom_X',
        if_neg (by decide : (1 : Fin 4) ≠ 0), if_pos (by decide : (1 : Fin 4) = 1)]
      exact chartYt_fin2 (0 : Fin 2) ⟨0, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, cuspYtToClosed,
        Ideal.Quotient.lift_mk, closedYtToCuspEval, cuspYtToClosedPoly,
        MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), MvPolynomial.eval₂Hom_X',
        if_neg (by decide : (2 : Fin 4) ≠ 0), if_neg (by decide : (2 : Fin 4) ≠ 1),
        if_pos (by decide : (2 : Fin 4) = 2)]
      exact chartYt_fin2 (1 : Fin 2) ⟨1, by decide⟩ rfl

private lemma cuspYtToClosed_comp_closedYtToCusp :
    cuspYtToClosed.comp closedYtToCusp = RingHom.id modelYtChart_fixed := by
  apply Ideal.Quotient.ringHom_ext
  apply MvPolynomial.ringHom_ext
  · intro r
    simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, closedYtToCuspEval,
      cuspYtToClosed, cuspYtToClosedPoly, Ideal.Quotient.lift_mk, MvPolynomial.eval₂Hom_C]
  · intro i
    fin_cases i
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, Ideal.Quotient.lift_mk,
        closedYtToCuspEval, MvPolynomial.eval₂Hom_X']
      rw [if_pos (by decide)]
      simp only [cuspYtToClosed, Ideal.Quotient.lift_mk, RingHom.comp_apply, cuspYtToClosedPoly,
        map_mul, MvPolynomial.eval₂Hom_X']
      rw [if_true, if_neg (by decide : (1 : Fin 2) ≠ 0)]
      rw [← map_mul (Ideal.Quotient.mk modelYtTrueIdeal_fixed), Ideal.Quotient.eq]
      rw [CharTwo.sub_eq_add, add_comm, ← CharTwo.sub_eq_add, modelYtTrueIdeal_fixed]
      exact Ideal.subset_span (Set.mem_insert _ _)
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, Ideal.Quotient.lift_mk,
        closedYtToCuspEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_pos (by decide)]
      simp only [cuspYtToClosed, Ideal.Quotient.lift_mk, RingHom.comp_apply, cuspYtToClosedPoly,
        MvPolynomial.eval₂Hom_X']
      rw [if_true]
      exact chartYt_fin4_fixed 1 ⟨1, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, Ideal.Quotient.lift_mk,
        closedYtToCuspEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_neg (by decide), if_pos (by decide)]
      simp only [cuspYtToClosed, Ideal.Quotient.lift_mk, RingHom.comp_apply, cuspYtToClosedPoly,
        MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide : (1 : Fin 2) ≠ 0)]
      exact chartYt_fin4_fixed 2 ⟨2, by decide⟩ rfl
    · simp only [RingHom.comp_apply, RingHom.id_apply, closedYtToCusp, Ideal.Quotient.lift_mk,
        closedYtToCuspEval, MvPolynomial.eval₂Hom_X']
      rw [if_neg (by decide), if_neg (by decide), if_neg (by decide)]
      simp only [cuspYtToClosed, Ideal.Quotient.lift_mk, RingHom.comp_apply]
      have hpoly : cuspYtToClosedPoly
          (MvPolynomial.X 0 + (MvPolynomial.X 0) ^ 2 * (MvPolynomial.X 1) ^ 3) =
          MvPolynomial.X 1 + (MvPolynomial.X 1) ^ 2 * (MvPolynomial.X 2) ^ 3 := by
        simp [cuspYtToClosedPoly, map_add, map_mul, map_pow, MvPolynomial.eval₂Hom_X']
      rw [hpoly, Ideal.Quotient.eq, CharTwo.sub_eq_add, add_comm, ← add_assoc]
      exact modelYt_fixed_witness_mem

/-- `X = Y·S` and `T = Y + Y²·S³` eliminate.
`𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal_fixed ≃+* 𝔽₂[a,b][Y,S] / (Y²·(1 − Y·S³))`. -/
noncomputable def modelYtTrueIdeal_elim :
    modelYtChart_fixed ≃+* chartYtCuspRing :=
  RingEquiv.ofRingHom closedYtToCusp cuspYtToClosed
    closedYtToCusp_comp_cuspYtToClosed cuspYtToClosed_comp_closedYtToCusp

theorem modelYtTrueIdeal_fixed_le_ker :
    modelYtTrueIdeal_fixed ≤ RingHom.ker chartYtModelEval := by
  rw [modelYtTrueIdeal_fixed, Ideal.span_le]
  intro z hz
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
  rcases hz with rfl | rfl | rfl
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_sub, map_mul, chartYtModelEval_X,
      chartYtModelEval_X, chartYtModelEval_X,
      if_pos (rfl : (0 : Fin 4) = 0),
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2),
      chartYt_X_eq_Y_mul_X_over_Y, sub_self]
  · rw [SetLike.mem_coe, RingHom.mem_ker]
    simpa [chartYtKernelWitness] using chartYtModelEval_kernelWitness
  · rw [SetLike.mem_coe, RingHom.mem_ker, map_mul, map_pow, map_sub, map_one, map_mul, map_pow,
      chartYtModelEval_X, chartYtModelEval_X,
      if_neg (by decide : (1 : Fin 4) ≠ 0),
      if_pos (rfl : (1 : Fin 4) = 1),
      if_neg (by decide : (2 : Fin 4) ≠ 0),
      if_neg (by decide : (2 : Fin 4) ≠ 1),
      if_pos (rfl : (2 : Fin 4) = 2)]
    exact chartYt_cusp_relation

/-- `𝔽₂[a,b][X,Y,S,T] / modelYtTrueIdeal_fixed → D₊(Yt)`.
`T` is sent to `Y + Y²·S³`, which is `2t/Yt`. -/
noncomputable def chartOfModelTrueY_fixed :
    modelYtChart_fixed →+* chart_Dplus_Yt_ring valuationOneCurve 0 0 :=
  Ideal.Quotient.lift modelYtTrueIdeal_fixed chartYtModelEval modelYtTrueIdeal_fixed_le_ker

/-- `Y` and `S = Xt/Yt` still generate `D₊(Yt)` after imposing `T = Y + Y²·S³`. -/
theorem chartOfModelTrueY_fixed_surjective :
    Function.Surjective chartOfModelTrueY_fixed := by
  intro z
  obtain ⟨p, hp⟩ := chartYtModelEval_surjective z
  refine ⟨Ideal.Quotient.mk modelYtTrueIdeal_fixed p, ?_⟩
  rw [chartOfModelTrueY_fixed, Ideal.Quotient.lift_mk]
  exact hp

#print axioms Beal.MathlibMissing.valuationOne_specialYT_pow_ne_zero
#print axioms Beal.MathlibMissing.chartOfModelTrueY_surjective
#print axioms Beal.MathlibMissing.chartYt_X_eq_Y_mul_X_over_Y
#print axioms Beal.MathlibMissing.chartYt_Y_mul_two_over_Y_eq_zero
#print axioms Beal.MathlibMissing.chartYt_Y_sq_eq_X_cu
#print axioms Beal.MathlibMissing.chartYt_cusp_relation
#print axioms Beal.MathlibMissing.chartYt_two_over_Y_sq_zero
#print axioms Beal.MathlibMissing.chartOfModelTrueY
#print axioms Beal.MathlibMissing.modelYtChart_quotient_equiv_normal
#print axioms Beal.MathlibMissing.chartYt_kernel_relation
#print axioms Beal.MathlibMissing.chartYtModelEval_kernelWitness
#print axioms Beal.MathlibMissing.chartYtKernelWitness_not_mem
#print axioms Beal.MathlibMissing.not_chartOfModelTrueY_injective
#print axioms Beal.MathlibMissing.modelYtTrueIdeal_fixed_mem_mul_YT
#print axioms Beal.MathlibMissing.modelYtTrueIdeal_fixed_mem_Tsq
#print axioms Beal.MathlibMissing.modelYtTrueIdeal_elim
#print axioms Beal.MathlibMissing.chartOfModelTrueY_fixed
#print axioms Beal.MathlibMissing.chartOfModelTrueY_fixed_surjective

end Beal.MathlibMissing
