import Beal.«Beal.General».TateEvenCoordinateCharts
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
import Mathlib.AlgebraicGeometry.Morphisms.UniversallyClosed
import Mathlib.RingTheory.ReesAlgebra

/-!
# Isolated gap: `Proj` properness

`BealEven` does not import this file. `lake build BealEven` does not
elaborate it.

`gradedSurjection_R_T_to_Rees` is a proved ring map. For an ideal
generated by three elements `s₀, s₁, s₂`, it sends `Tᵢ` to the
degree-one Rees monomial `sᵢ t`. It is surjective. It is not a
morphism of `Proj`, and it is not a closed immersion into `ℙ²`.

`proj_proper_of_fg_graded_gap` is uninhabited. No `sorry` is used.
-/

namespace Beal.MathlibMissing

open Beal.General Polynomial

/-- `R[T₀,T₁,T₂] → Rees(I)` for `I = (s₀, s₁, s₂)`, sending `Tᵢ` to
the degree-one monomial `sᵢ t`. -/
noncomputable def gradedSurjection_R_T_to_Rees
    {R : Type} [CommRing R] (s : Fin 3 → R) :
    MvPolynomial (Fin 3) R →+*
      reesAlgebra (Ideal.span (Set.range s)) :=
  (MvPolynomial.aeval (fun i =>
    centreReesDegreeOne (Ideal.span (Set.range s)) (s i)
      (Ideal.subset_span ⟨i, rfl⟩))).toRingHom

/-- `Tᵢ` lands in degree one of the Rees grading. -/
theorem gradedSurjection_R_T_to_Rees_degree_one
    {R : Type} [CommRing R] (s : Fin 3 → R) (i : Fin 3) :
    gradedSurjection_R_T_to_Rees s (MvPolynomial.X i) ∈
      centreReesComponent (Ideal.span (Set.range s)) 1 := by
  simpa [gradedSurjection_R_T_to_Rees, MvPolynomial.aeval_X] using
    centreReesDegreeOne_mem (Ideal.span (Set.range s)) (s i)
      (Ideal.subset_span ⟨i, rfl⟩)

/-- The three degree-one monomials generate the Rees algebra, so the
polynomial map is surjective. -/
theorem gradedSurjection_R_T_to_Rees_surjective
    {R : Type} [CommRing R] (s : Fin 3 → R) :
    Function.Surjective (gradedSurjection_R_T_to_Rees s) := by
  classical
  let I := Ideal.span (Set.range s)
  let g : Fin 3 → reesAlgebra I := fun i =>
    centreReesDegreeOne I (s i) (Ideal.subset_span ⟨i, rfl⟩)
  let φ : MvPolynomial (Fin 3) R →ₐ[R] reesAlgebra I := MvPolynomial.aeval g
  change Function.Surjective (φ : MvPolynomial (Fin 3) R → reesAlgebra I)
  intro p
  have hadjoin :
      Algebra.adjoin R
        ((Polynomial.monomial 1 : R →ₗ[R] R[X]) '' Set.range s) =
      reesAlgebra I := by
    rw [← adjoin_monomial_eq_reesAlgebra]
    have hsub :=
      Submodule.map_span (Polynomial.monomial 1 : R →ₗ[R] R[X]) (Set.range s)
    have hI : (I : Submodule R R) = Submodule.span R (Set.range s) := rfl
    rw [← hI] at hsub
    rw [hsub, Algebra.adjoin_span]
  have himage :
      (Subalgebra.val (reesAlgebra I) : reesAlgebra I → R[X]) '' Set.range g =
        (Polynomial.monomial 1 : R →ₗ[R] R[X]) '' Set.range s := by
    ext x
    constructor
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      refine ⟨s i, ⟨i, rfl⟩, ?_⟩
      simp [g, centreReesDegreeOne]
    · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
      refine ⟨g i, ⟨i, rfl⟩, ?_⟩
      simp [g, centreReesDegreeOne]
  have hmap :
      (Algebra.adjoin R (Set.range g)).map (Subalgebra.val (reesAlgebra I)) =
        reesAlgebra I := by
    rw [AlgHom.map_adjoin, himage, hadjoin]
  have hmem : (p : R[X]) ∈
      (Algebra.adjoin R (Set.range g)).map (Subalgebra.val (reesAlgebra I)) := by
    rw [hmap]
    exact SetLike.coe_mem p
  obtain ⟨q, hq, hqeq⟩ := Subalgebra.mem_map.mp hmem
  have hqp : q = p := Subtype.ext hqeq
  rw [hqp] at hq
  have hrange : Algebra.adjoin R (Set.range g) = (MvPolynomial.aeval g).range := by
    simp only [← Algebra.map_top, ← MvPolynomial.adjoin_range_X, AlgHom.map_adjoin,
      ← Set.range_comp, Function.comp_def, MvPolynomial.aeval_X]
  rw [hrange] at hq
  obtain ⟨poly, hpoly⟩ :=
    (AlgHom.mem_range (φ := MvPolynomial.aeval g) (y := p)).mp hq
  exact ⟨poly, hpoly⟩

/-- The translated surface centre is the ideal generated by the three
scalars `2`, `X`, and `Y`, so the general surjection applies to it.
The codomain is `Rees` of that span, which
`localSurfaceCentreScalars_span` identifies with the closed point. -/
noncomputable def localSurfaceCentre_gradedSurjection
    (W : WeierstrassCurve ℤ_[2]) (x y : ℤ_[2]) :
    MvPolynomial (Fin 3) (localSurfaceCoordinateRing W x y) →+*
      reesAlgebra (Ideal.span
        (Set.range (localSurfaceCentreScalars W x y))) :=
  gradedSurjection_R_T_to_Rees (localSurfaceCentreScalars W x y)

theorem localSurfaceCentre_gradedSurjection_surjective
    (W : WeierstrassCurve ℤ_[2]) (x y : ℤ_[2]) :
    Function.Surjective (localSurfaceCentre_gradedSurjection W x y) :=
  gradedSurjection_R_T_to_Rees_surjective _

theorem localSurfaceCentre_gradedSurjection_degree_one
    (W : WeierstrassCurve ℤ_[2]) (x y : ℤ_[2]) (i : Fin 3) :
    localSurfaceCentre_gradedSurjection W x y (MvPolynomial.X i) ∈
      centreReesComponent
        (Ideal.span (Set.range (localSurfaceCentreScalars W x y))) 1 :=
  gradedSurjection_R_T_to_Rees_degree_one _ i

theorem localSurfaceCentre_gradedSurjection_ideal
    (W : WeierstrassCurve ℤ_[2]) (x y : ℤ_[2]) :
    Ideal.span (Set.range (localSurfaceCentreScalars W x y)) =
      localSurfaceClosedPoint W x y :=
  (localSurfaceCentreScalars_span W x y).symm

/-- OPEN. What is still missing after the graded surjection.

Mathlib v4.12.0 has no scheme `ℙ²_R`, so properness of
`ℙ²_R → Spec(R)` is not a term. A surjective graded map
`R[T₀,T₁,T₂] → Rees(I)` does not induce a morphism of `Proj`, so
`Proj(Rees) → ℙ²_R` is not a term and is not a closed immersion.
`IsClosedImmersion` is not shown to be stable under pullback and is
not shown to be `UniversallyClosed`. The body is that last
implication, in the universe of `Spec` of a ring in `Type`. No
inhabitant is given, and this file is not imported by `BealEven`. -/
def proj_proper_of_fg_graded_gap : Prop :=
  ∀ (S T : AlgebraicGeometry.Scheme.{0}) (f : S ⟶ T),
    AlgebraicGeometry.IsClosedImmersion f →
    AlgebraicGeometry.UniversallyClosed f

end Beal.MathlibMissing

#print axioms Beal.MathlibMissing.gradedSurjection_R_T_to_Rees_surjective
#print axioms Beal.MathlibMissing.gradedSurjection_R_T_to_Rees_degree_one
#print axioms Beal.MathlibMissing.localSurfaceCentre_gradedSurjection_surjective
#print axioms Beal.MathlibMissing.proj_proper_of_fg_graded_gap
